const AllCategories = [
    {   
        id: 1,
        Image: require("../assets/images/webSeries/bambai.jpg"),
        name: "Bambai Meri Jaan (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Nawab Shah, Sunil Palwal, Jay Singh Rajpoot",
        geners: "Crime, Drama",
        screenShot: require("../assets/images/webSeries/bambaiOne.jpg"),
        writers: "Shujaat Saudagar",
        imdb: "N/A/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A sneak into the post-independence Bombay and streets riddled with crime. An honest cop’s journey as he tries to protect his family.",
        movieLink: "https://ssrmovies.yachts/bambai-meri-jaan-2023-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {
        id: 2,
        Image: require("../assets/images/south/balupu.jpg"),
        name: "Balupu (2013) 1080p 720p 480p WEB-DL x264",
        star: "Ravi Teja, Shruti Haasan, Anjali",
        geners: "Action, Comedy",
        screenShot: require("../assets/images/south/balupuOne.jpg"),
        writers: "Kona Venkat, K.S. Ravindra, Veligonda Srinivas",
        imdb: "6.1/10",
        director: "Gopichand Malineni",
        language: "Hindi (ORG 2.0)",
        story: "Ravi (Ravi Teja) works as a collection agent of ICICI in Bangalore and leads a happy life along with his friends and his father Mohan Rao (Prakash Raj) who wishes to see Ravi married to a girl soon. Once Ravi rushes to a Hospital where his friend (‘Satyam’ Rajesh) is admitted as he tried to commit suicide by drinking nail polish solution and asks the reason for it. Then he describes about the traits of Shruti (Shruti Haasan) and her uncle Crazy Mohan (Brahmanandam). The duo have a habit of cheating gullible young men including his friend and Ravi decides to teach them a lesson.",
        movieLink: "https://ssrmovies.yachts/balupu-2013-hindi-dubbed-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 3,
        Image: require("../assets/images/webSeries/breaking.jpg"),
        name: "Breaking (2022) 1080p 720p 480p WEB-DL x264",
        star: "John Boyega, Nicole Beharie, Selenis Leyva",
        geners: "Crime, Drama, Thriller",
        screenShot: require("../assets/images/webSeries/breakingOne.jpg"),
        writers: "Abi Damaris Corbin, Kwame Kwei-Armah",
        imdb: "6.8/10",
        director: "Abi Damaris Corbin",
        language: "Hindi (ORG 2.0)",
        story: "A Marine war veteran faces mental and emotional challenges when he tries to reintegrate back into civilian life.",
        movieLink: "https://ssrmovies.yachts/breaking-bad-s04/"
    },
    {
        id: 4,
        Image: require("../assets/images/hollywood/barbie.jpg"),
        name: "Barbie (2023) 1080p 720p 480p HC WEB-DL x264",
        star: "Margot Robbie, Ryan Gosling, Issa Rae",
        geners: "Adventure, Comedy, Fantasy",
        screenShot: require("../assets/images/hollywood/barbieOne.jpg"),
        writers: "Greta Gerwig, Noah Baumbach",
        imdb: "7.4/10",
        director: "Greta Gerwig",
        language: "English (ORG)",
        story: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        movieLink: "https://ssrmovies.yachts/barbie-2023-english-1080p-720p-480p-hdts-x264/"
    },
    {
        id: 5,
        Image: require("../assets/images/bollywood/afwah.jpg"),
        name: "Afwaah 1080p 720p 480p WEB-DL x264",
        star: "Bhumi Pednekar, Nawazuddin Siddiqui, Sumeet Vyas",
        geners: "Drama, Thriller",
        screenShot: require("../assets/images/bollywood/afwahOne.jpg"),
        writers: "Apurva Dhar Badgaiyan, Shiva Shankar Bajpai, Nisarg Mehta",
        imdb: "4.9/10",
        director: "Sudhir Mishra",
        language: "Hindi(ORG 5.1)",
        story: "An advertising professional and a political heiress whose lives are upended by a viral social media rumour.",
        movieLink: "https://ssrmovies.yachts/afwaah-2023-nf-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 6,
        Image: require("../assets/images/webSeries/campus.jpg"),
        name: "Campus Beats (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Shantanu Maheshwari, Shruti Sinha, Sahaj Singh",
        geners: "Drama",
        screenShot: require("../assets/images/webSeries/campusOne.jpg"),
        writers: "N/A",
        imdb: "10.0/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "What starts as an agenda to get closure for her past , a GenZ girl uncovers her hidden dancing talent and in the process experiences the real meaning of friendship, love, freedom and justice in a modern dance academy divided sharply across socio-economic class.",
        movieLink: "https://ssrmovies.yachts/?s=Campus+Beats"
    },
    {
        id: 7,
        Image: require("../assets/images/bollywood/ajmer.jpg"),
        name: "Ajmer 92 1080p 720p 480p WEB-DL x264",
        star: "Alka Amin, Mahesh Balraj, Aakash Dahiya",
        geners: "Drama",
        screenShot: require("../assets/images/bollywood/ajmerOne.jpg"),
        writers: "Suraj Pal Rajak, Gyanendra Pratap Singh, Pushpendra Singh",
        imdb: " 8.9/10",
        director: "Pushpendra Singh",
        language: "Hindi (CAM)",
        story: "A heart-wrenching story of 250 girls from Ajmer. Ajmer 92 releasing in cinemas on 14th July.",
        movieName: "https://ssrmovies.yachts/ajmer-92-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {
        id: 8,
        Image: require("../assets/images/hollywood/best.jpg"),
        name: "The Best Man (2023) 1080p 720p 480p WEB-DL x264",
        star: "Brendan Fehr, Nicky Whelan, Scout Taylor-Compton",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/hollywood/bestOne.jpg"),
        writers: "C. Alec Rossel, Shane Dax Taylor, Daniel Zirilli",
        imdb: "4.1/10",
        director: "Shane Dax Taylor",
        language: "English (ORG)",
        story: "Mercenaries seize control of a remote resort hotel during a wedding and it’s up to the best man, the groom and their drunken best friend to stop the terrorists and save the hostages.",
        movieLink: "https://ssrmovies.yachts/the-best-man-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 9,
        Image: require("../assets/images/webSeries/charli.jpg"),
        name: "Charlie Chopra & The Mystery of Solang Valley (2023) 1080p 720p 480p WEB-DL x264",
        star: "Wamiqa Gabbi, Lara Dutta, Naseeruddin Shah",
        geners: "Mystery",
        screenShot: require("../assets/images/webSeries/charliOne.jpg"),
        writers: "N/A",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A rich man dead, a town full of suspects, narratives filled with lies and an innocent convict. How will Charlie navigate through the mystery when every face hides a secret?",
        movieLink: "https://ssrmovies.yachts/charlie-chopra-the-mystery-of-solang-valley-2023-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 10,
        Image: require("../assets/images/south/bholla.jpg"),
        name: "Bholaa Shankar (2023) 1080p 720p 480p WEB-DL x264",
        star: "Chiranjeevi, Tamannaah Bhatia, Keerthy Suresh",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/bhollaOne.jpg"),
        writers: "Adi Narayana, Siva, Mamidala Thirupathi",
        imdb: "3.2/10",
        director: "Meher Ramesh",
        language: "Hindi (ORG 5.1)",
        story: "A doting brother tries to hunt down notorious criminals who had harmed his sister.",
        movieLink: "https://ssrmovies.yachts/bholaa-shankar-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 11,
        Image: require("../assets/images/hollywood/big.jpg"),
        name: "Big George Foreman (2023) 1080p 720p 480p BluRay x264",
        star: "Khris Davis, Jasmine Mathews, Sullivan Jones",
        geners: "Biography, Drama, Sport",
        screenShot: require("../assets/images/hollywood/bigOne.jpg"),
        writers: "Frank Baldwin, George Tillman Jr., Dan Gordon",
        imdb: "6.5/10",
        director: "George Tillman Jr.",
        language: "English (ORG)",
        story: "Follow the remarkable life and times of Foreman, from Olympic Gold medalist to World Heavyweight champion, the Rumble in the Jungle fight with Muhammad Ali in Zaire, to finding his faith, retiring, and becoming a preacher. When financial hardship hits his family and church, he steps back in the ring and regains the championship at age 45, becoming the oldest heavyweight champion in boxing history.",
        movieLink: "https://ssrmovies.yachts/big-george-foreman-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 12,
        Image: require("../assets/images/webSeries/continentel.jpg"),
        name: "The Continental: From the World of John Wick (2023) 1080p 720p 480p WEB-DL x264",
        star: "Mel Gibson, Colin Woodell, Mishel Prada",
        geners: "Action, Crime, Thriller",
        screenShot: require("../assets/images/webSeries/continentelOne.jpg"),
        writers: "Greg Coolidge, Shawn Simmons, Kirk Ward",
        imdb: "7.8/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Set in 1970s New York City, The Continental explores the origin of the iconic hotel-for-assassins centerpiece of the John Wick universe seen through the eyes and action of a young Winston Scott.",
        movieLink: "https://ssrmovies.yachts/the-continental-from-the-world-of-john-wick-2023-s01-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {
        id: 13,
        Image: require("../assets/images/bollywood/akelli.jpg"),
        name: "Akelli (2023) 1080p 720p 480p WEB-DL x264",
        star: "Nushrratt Bharuccha, Tsahi Halevi, Amir Boutrous",
        geners: "Drama, Thriller",
        screenShot: require("../assets/images/bollywood/akelliOne.jpg"),
        writers: "Pranay Meshram, Gunjan Saxena, Ayush Tiwari",
        imdb: "N/A/10",
        director: "Pranay Meshram",
        language: "Hindi (CAM)",
        story: "A middle class girl Jyoti. Who deals with financial issues. The story shows how Jyoti tackle those obstacles.",
        movieLink: "https://ssrmovies.yachts/akelli-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {
        id: 14,
        Image: require("../assets/images/south/chatrapati.jpg"),
        name: "Chatrapathi (2023) 1080p 720p 480p HDTV x264",
        star: "Sai Srinivas Bellamkonda, Nushrratt Bharuccha, Karan Singh Chhabra",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/chatrapatiOne.jpg"),
        writers: "A. Mahadev, Vijayendra Prasad, Mayur Puri",
        imdb: "8.8/10",
        director: "V.V. Vinayak",
        language: "Hindi (ORG 2.0)",
        story: "Shivaji and his family are uprooted from their community in Sri Lanka and wind up as bonded labourers in Visakhapatnam. The situation worsens when his jealous stepbrother enters his life.",
        movieLink: "https://ssrmovies.yachts/chatrapathi-2023-hindi-org-2-0-1080p-720p-480p-hdtv-x264/"
    },
    {   
        id: 15,
        Image: require("../assets/images/webSeries/groot.jpg"),
        name: "I Am Groot (2023) S02 1080p 720p 480p WEB-DL x264",
        star: "Vin Diesel, Fred Tatasciore, Kaitlyn Robrock",
        geners: "Animation, Short, Action",
        screenShot: require("../assets/images/webSeries/grootOne.jpg"),
        writers: "N/A",
        imdb: "6.7/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A series of shorts featuring the seedling Groot along with several new and unusual characters.",
        movieLink: "https://ssrmovies.yachts/i-am-groot-2023-s02-english-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 16,
        Image: require("../assets/images/bollywood/bawal.jpg"),
        name: "Bawaal (2023) 1080p 720p 480p WEB-DL x264",
        star: "Varun Dhawan, Janhvi Kapoor, Parth Siddhpura",
        geners: "Action, Drama, Romance",
        screenShot: require("../assets/images/bollywood/bawalOne.jpg"),
        writers: "Piyush Gupta, Shreyas Jain, Nikhil Mehrotra",
        imdb: "N/A/10",
        director: "Nitesh Tiwari",
        language: "Hindi (ORG 5.1)",
        story: "A small-town man who falls in love with the most beautiful girl in town. He wants to marry her one day because marrying her can rise up his social position.",
        movieLink: "https://ssrmovies.yachts/?s=Bawaal"
    },
    {
        id: 17,
        Image: require("../assets/images/south/golondaaj.jpg"),
        name: "Golondaaj (2021) 1080p 720p 480p WEB-DL x264",
        star: "Dev, Alexx O’Nell, Srikanta Acharya",
        geners: "Sport",
        screenShot: require("../assets/images/south/golondaajOne.jpg"),
        writers: "Dhrubo Banerjee, Anirban Bhattacharya, Ruchita Chatterji",
        imdb: "7.3/10",
        director: "Dhrubo Banerjee",
        language: "Hindi (ORG 2.0)",
        story: "The life of Nagendra Prasad Sarbadhikari, who is known as the father of Indian football at a time when football lovers dared to take on the British and chalk their own identity.",
        movieLink: "https://ssrmovies.yachts/golondaaj-2021-hindi-org-1080p-720p-480p-web-dl-x264/"
    },
    {   
        id: 18,
        Image: require("../assets/images/webSeries/lucky.jpg"),
        name: "Lucky Guy (2023) S01 720p 480p WEB-DL x264",
        star: "Swagger Sharma, Ankur Pathak, Gauri Chakraborty",
        geners: "Drama, Fantasy",
        screenShot: require("../assets/images/webSeries/luckyOne.jpg"),
        writers: "N/A",
        imdb: "9.0/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The story revolves around a guy named “Lucky” who is apparently the luckiest guy in the world . What happens when he losses his luck after living with it for 20 years of his life . Will he be able to fight back . The story starts from the birth of a child who happens to take birth in an extraordinary positioning of planets favouring his fate forever.",
        movieLink: "https://ssrmovies.yachts/lucky-guy-2023-s01-complete-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 19,
        Image: require("../assets/images/hollywood/bital.jpg"),
        name: "Blue Beetle (2023) 1080p 720p 480p WEB-DL x264",
        star: "Xolo Maridueña, Bruna Marquezine, Becky G",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/hollywood/bitalOne.jpg"),
        writers: "Gareth Dunnet-Alcocer",
        imdb: "6.7/10",
        director: "Angel Manuel Soto",
        language: "English (ORG)",
        story: "An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor that’s capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blu…",
        movieLink: "https://ssrmovies.yachts/blue-beetle-2023-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 20,
        Image: require("../assets/images/webSeries/mask.jpg"),
        name: "Mask Girl (2023)  S01 720p 480p WEB-DL x264",
        star: "Anzu Lawson, Yeom Hye-ran, Jin-Ah Im",
        geners: "Comedy, Drama, Thriller",
        screenShot: require("../assets/images/webSeries/maskOne.jpg"),
        writers: "N/A",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "An office worker who is insecure about her looks becomes a masked internet personality by night until a chain of ill-fated events overtakes her life.",
        movieLink: "https://ssrmovies.yachts/mask-girl-2023-s01-complete-dual-audio-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 21,
        Image: require("../assets/images/south/ips.jpg"),
        name: "IPC 376 (2021) 1080p 720p 480p WEB-DL x264",
        star: "Nandita Shwetha, Aryan, Meghana Ellen",
        geners: "Drama, Horror, Mystery",
        screenShot: require("../assets/images/south/ipsOne.jpg"),
        writers: "Ramkumar",
        imdb: "4.0/10",
        director: "Ramkumar",
        language: "Hindi (ORG 2.0)",
        story: "The plot revolves around a police inspector and an unknown informer who conveys about future murders in a mysterious way. Will she be able to find the informer?",
        movieLink: "https://ssrmovies.yachts/ipc-376-2021-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 22,
        Image: require("../assets/images/bollywood/blind.jpg"),
        name: "Blind (2023) 1080p 720p 480p WEB-DL x264",
        star: "Sonam Kapoor, Lucy Aarden, Lillete Dubey",
        geners: "Crime, Drama, Thriller",
        screenShot: require("../assets/images/bollywood/blindOne.jpg"),
        writers: "Shome MakhijaSudeep Nigam",
        imdb: "N/A",
        director: "Shome Makhija",
        language: "Hindi (ORG 5.1)",
        story: "When a twist of fate leaves Gia blind, she must summon every ounce of courage to rebuild her life. But when she becomes the sole witness to a heinous crime, she unwittingly enters a deadly game of cat and mouse with a dangerous criminal.",
        movieLink: "https://ssrmovies.yachts/blind-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 23,
        Image: require("../assets/images/webSeries/my.jpg"),
        name: "MY3 2023 S01 1080p 720p 480p WEB-DL x264",
        star: "Hansika Motwani, Janani Iyer, Shanthnu Bhagyaraj",
        geners: "Comedy, Drama, Sci-Fi",
        screenShot: require("../assets/images/webSeries/myOne.jpg"),
        writers: "M Rajesh’s",
        imdb: "7.3/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The series follows the story of a woman named Jaan (Hansika Motwani) who wakes up in a laboratory with no memory of her past. She soon discovers that she is a robot created by a scientist named Dr. Ashutosh (Mugen Rao). Jaan must now learn to control her powers and use them to stop a mysterious organization that is trying to take over the world.",
        movieLink: "https://ssrmovies.yachts/my3-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 24,
        Image: require("../assets/images/hollywood/black.jpg"),
        name: "The Black Demon (2023) 1080p 720p 480p BluRay x264",
        star: "Omar Chaparro, Bolivar Sanchez, Carlos Solórzano",
        geners: "Horror, Sci-Fi, Thriller",
        screenShot: require("../assets/images/hollywood/blackOne.jpg"),
        writers: "Carlos Cisco, Boise Esquerra",
        imdb: "3.7/10",
        director: "Adrian Grunberg",
        language: "English (ORG)",
        story: "tranded on a crumbling rig in Baja, a family faces off against a vengeful megalodon shark.",
        movieLink: "https://ssrmovies.yachts/the-black-demon-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {
        id: 25,
        Image: require("../assets/images/hollywood/covenent.jpg"),
        name: "The Covenant (2023) 1080p 720p 480p BluRay x264",
        star: "Jake Gyllenhaal, Dar Salim, Sean Sagar",
        geners: "Action, Thriller, War",
        screenShot: require("../assets/images/hollywood/covenentOne.jpg"),
        writers: "Guy Ritchie, Ivan Atkinson, Marn Davies",
        imdb: "7.5/10",
        director: "Guy Ritchie",
        language: "English (ORG)",
        story: "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
        movieLink: "https://ssrmovies.yachts/the-covenant-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 26,
        Image: require("../assets/images/webSeries/one.jpg"),
        name: "One Piece (2023) S01 NF 720p 480p WEB-DL x264",
        star: "Iñaki Godoy, Mackenyu, Emily Rudd",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/webSeries/oneOne.jpg"),
        writers: "Steven Maeda, Matt Owens",
        imdb: "8.7/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as ‘One Piece.",
        movieLink: "https://ssrmovies.yachts/one-piece-2023-s01-complete-nf-dual-audio-hindi-org-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 27,
        Image: require("../assets/images/webSeries/song.jpg"),
        name: "Song of the Bandits (2023) NF S01 1080p 720p 480p WEB-DL x264",
        star: "Kim Nam-gil, Seohyun, Yoo Jae-myung",
        geners: "Action, Drama, History",
        screenShot: require("../assets/images/webSeries/songOne.jpg"),
        writers: "N/A",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The Koreans who gathered in Gando, today part of northeastern China, for their own reasons and band together to protect their homes during 1910-45 Japanese colonial rule.",
        movieLink: "https://ssrmovies.yachts/song-of-the-bandits-2023-s01-complete-nf-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 28,
        Image: require("../assets/images/south/virupaksa.jpg"),
        name: "Virupaksha (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Sai Dharam Tej, Ajay, Rajsekhar Aningi",
        geners: "Action, Drama, Mystery",
        screenShot: require("../assets/images/south/virupaksaOne.jpg"),
        writers: "Sukumar",
        imdb: "8.3/10",
        director: "Karthik Varma Dandu",
        language: "Hindi (ORG 2.0)",
        story: "Mysterious deaths occur in a village due to an unknown person’s occult practice. The whole town is scared of these killings. Will they find the person who causes the deaths? ,problems faced during the process is the rest of the st…",
        movieLink: "https://ssrmovies.yachts/virupaksha-2023-uncut-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 29,
        Image: require("../assets/images/bollywood/farhana.jpg"),
        name: "Farhana (2023) 1080p 720p 480p WEB-DL x264",
        star: "Aishwarya Rajesh, K. Selvaraghavan, Anumol K. Manoharan",
        geners: "Drama, Thriller",
        screenShot: require("../assets/images/bollywood/farhanaOne.jpg"),
        writers: "Sankar Dass, Renjith Ravindran, Nelson Venkatesan",
        imdb: "5.9/10 ",
        director: "Nelson Venkatesan",
        language: "Hindi (ORG)",
        story: "A middle-class mother takes a call centre job due to her financial reasons, and that gives her freedom, but it leads into a web of dangers.",
        movieLink: "https://ssrmovies.yachts/farhana-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 30,
        Image: require("../assets/images/south/kabzaa.jpg"),
        name: "Kabzaa (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Upendra, Sudeep, Shriya Saran",
        geners: "Action, Crime, Drama",
        screenShot: require("../assets/images/south/kabzaaOne.jpg"),
        writers: "M Chandramouli, R. Chandru",
        imdb: "8.9/10",
        director: "R. Chandru",
        language: "Hindi (ORG 2.0)",
        story: "In 1947 a Gandhi follower and a freedom fighter were brutally attacked. Due to unavoidable circumstances, the freedom fighter son gets trapped in the mafia world and the story revolves between 1942 to 1986.",
        movieLink: "https://ssrmovies.yachts/kabzaa-2023-amzn-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 31,
        Image: require("../assets/images/webSeries/ragnarok.jpg"),
        name: "Ragnarok (2023) S03 NF 720p 480p WEB-DL x264",
        star: "David Stakston, Jonas Strand Gravli, Herman Tømmeraas",
        geners: "Action, Drama, Fantasy",
        screenShot: require("../assets/images/webSeries/ragnarokOne.jpg"),
        writers: "Emilie Lebech Kaae, Adam Price",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "In the small fictional town of Edda coming of age people are forced to respond to climate changes. The ice caps are melting at a rate no one had anticipated. People go through long periods of drought. The winters are too warm. More and more frequently, people experience extreme cold bursts. In all ways extreme weather conditions. The world is changing, and some might claim that we’re heading towards a new Ragnarok. Unless someone intervenes in time.",
        movieLink: "https://ssrmovies.yachts/ragnarok-2023-s03-complete-nf-dual-audio-hindi-org-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 32,
        Image: require("../assets/images/south/vathii.jpg"),
        name: "Vaathi (2023) NF 1080p 720p 480p WEB-DL x264",
        star: "Dhanush, Samyuktha Menon, Sai Kumar",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/vathiiOne.jpg"),
        writers: "Venky Atluri",
        imdb: "7.9/10",
        director: "Venky Atluri",
        language: "Hindi (ORG 2.0)",
        story: "The life of a young man and his struggles against the privatization of education.",
        movieLink: "https://ssrmovies.yachts/vaathi-2023-nf-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 33,
        Image: require("../assets/images/webSeries/shelter.jpg"),
        name: "Harlan Coben’s Shelter (2023) S01 720p 480p WEB-DL x264",
        star: "6.0/10",
        geners: "Crime, Drama, Mystery",
        screenShot: require("../assets/images/webSeries/shelterOne.jpg"),
        writers: "N/A",
        imdb: "6.0/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The story of Mickey Bolitar and his new life with a mom in rehab, a dead father, an annoying aunt, and a new school in New Jersey.",
        movieLink: "https://ssrmovies.yachts/harlan-cobens-shelter-2023-s01-complete-dual-audio-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 34,
        Image: require("../assets/images/bollywood/firangi.jpg"),
        name: "Firangi (2017) 1080p 720p 480p WEB-DL x264",
        star: "Kapil Sharma, Ishita Dutta, Monica Gill",
        geners: "Comedy, Drama",
        screenShot: require("../assets/images/bollywood/firangiOne.jpg"),
        writers: "Rupinder Chahal, Rajesh Chawla, Rajiv Dhingra",
        imdb: "4.3/10",
        director: "Rajiv Dhingra",
        language: "Hindi (ORG)",
        story: "Manga, an unemployed young man from village Behrampur, was born with a healing gift through which he could cure anyone’s backache. This unique ability of his helps him get the job of Orderly from British Officer Mark Daniels. During a visit to village Naku Guda for his friend Heera’s wedding, Manga comes across Sargi and falls in love with her. Manga’s parents visit Sargi’s house with a marriage proposal but Lalaji, Sargi’s grandfather, who is not happy with Manga working for the Britishers, refuses the proposal.",
        movieLink: "https://ssrmovies.yachts/firangi-2017-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 35,
        Image: require("../assets/images/webSeries/sach.jpg"),
        name: "Aakhri Sach (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Sanjiv Chopra, Tamannaah Bhatia, Kriti Vij",
        geners: "Thriller",
        screenShot: require("../assets/images/webSeries/sachOne.jpg"),
        writers: "Saurav Dey",
        imdb: "5.6/10",
        director: "Robbie Grewal",
        language: "Hindi (ORG 2.0)",
        story: "A bone chilling history that unravels the twisted ties of fate, hidden secrets of a family and terrifying horrors an investigator has ever seen.",
        movieLink: "https://ssrmovies.yachts/aakhri-sach-2023-s01/"
    },
    {
        id: 36,
        Image: require("../assets/images/hollywood/crater.jpg"),
        name: "Crater (2023) 1080p 720p 480p WEB-DL x264",
        star: "Mckenna Grace, Brady Noon, Billy Barratt",
        geners: "Adventure, Drama, Family",
        screenShot: require("../assets/images/hollywood/craterOne.jpg"),
        writers: "John Griffin",
        imdb: "4.7/10",
        director: "Kyle Patrick Alvarez",
        language: "English (ORG)",
        story: "After the death of his father, a boy growing up on a lunar mining colony takes a trip to explore a legendary crater, along with his four best friends, prior to being permanently relocated to another planet.",
        movieLink: "https://ssrmovies.yachts/crater-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 37,
        Image: require("../assets/images/south/thunivu.jpg"),
        name: "Thunivu (2023) NF 1080p 720p 480p WEB-DL x264",
        star: "Amir, Cibi Bhuvana Chandran, Darshan",
        geners: "Action, Adventure, Thriller",
        screenShot: require("../assets/images/south/thunivuOne.jpg"),
        writers: "H. Vinoth",
        imdb: "7.2/10",
        director: "H. Vinoth",
        language: "Hindi (ORG 2.0)",
        story: "A mysterious mastermind and his team forms a plan and commits bank heists across Chennai, but their motive of the heists remains mysterious.",
        movieLink: "https://ssrmovies.yachts/thunivu-2023-nf-hindi-org-1080p-720p-480p-nf-web-dl-x264-esubs/"
    },
    {   
        id: 38,
        Image: require("../assets/images/webSeries/sex.jpg"),
        name: "Sex Education (2023) S04 NF 1080p 720p 480p WEB-DL x264",
        star: "Asa Butterfield, Gillian Anderson, Ncuti Gatwa",
        geners: "Comedy, Drama",
        screenShot: require("../assets/images/webSeries/sexOne.jpg"),
        writers: "Laurie Nunn",
        imdb: "8.3/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Socially awkward high school student Otis may not have much experience in the lovemaking department, but he gets good guidance on the topic in his personal sex ed course — living with mom Jean, who is a sex therapist. Being surrounded by manuals, videos and tediously open conversations about sex, Otis has become a reluctant expert on the subject. When his classmates learn about his home life, Otis decides to use his insider knowledge to improve his status at school, so he teams with whip-smart bad girl Maeve to set up an underground sex therapy clinic to deal with their classmates’ problems. But through his analysis of teenage sexuality, Otis realizes that he may need some therapy of his own.",
        movieLink: "https://ssrmovies.yachts/sex-education-2023-s04-complete-nf-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {
        id: 39,
        Image: require("../assets/images/bollywood/gadar.jpg"),
        name: "Gadar 2 (2023) V2 1080p 720p 480p HDTS x264",
        star: "Sunny Deol, Ameesha Patel, Utkarsh Sharma",
        geners: "Action, Drama",
        screenShot: require("../assets/images/bollywood/gadarOne.jpg"),
        writers: "Shaktimaan Talwar",
        imdb: "7.2/10",
        director: "Anil Sharma",
        language: "Hindi (CAM)",
        story: "India’s most loved family of Tara, Sakeena and Jeete; 22 years after its predecessor. Set against the Indo-Pakistan war of 1971, Tara Singh, once again, will face every enemy to protect the honor of country and family.",
        movieLink: "https://ssrmovies.yachts/gadar-2-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 40,
        Image: require("../assets/images/webSeries/scam.jpg"),
        name: "Scam 2003 – The Telgi Story (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Gagandev Riar, Mukesh Tiwari, Sana Amin Sheikh",
        geners: "Biography, Crime, Drama",
        screenShot: require("../assets/images/webSeries/scamOne.jpg"),
        writers: "N/A",
        imdb: "9.9/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Scam 2003 is the story of Abdul Telgi from fruit seller to the kingpin of the stamp paper scam. In the chase for quick money, he lands on the wrong side of the law. With the help of a corrupt system, he rapidly monopolizes the stamp market, feeding everyone in the food chain, carefully maintaining a low profile. But his success and ego get the better of him.",
        movieLink: "https://ssrmovies.yachts/scam-2003-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 41,
        Image: require("../assets/images/bollywood/ghoomer.jpg"),
        name: "Ghoomer (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Amitabh Bachchan, Shabana Azmi, Abhishek Bachchan",
        geners: "Drama, Sport",
        screenShot: require("../assets/images/bollywood/ghoomerOne.jpg"),
        writers: "R. Balki, Rahul Sengupta, Rishi Virmani",
        imdb: "9.7/10",
        director: "R.Balki",
        language: "Hindi (CAM)",
        story: "Inspired by the incredible achievement of Karoly Takacs, follow the achievements of special athletes, and who have achieved more than when they were called “normal”.",
        movieLink: "https://ssrmovies.yachts/ghoomer-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {   
        id: 42,
        Image: require("../assets/images/webSeries/secret.jpg"),
        name: "Secret Ingredient 2023 (Part -2) 1080p 720p WEB-DL x264",
        star: "Pooja Singh, Payal Patil, Varun Sagar, Smita Paul",
        geners: "Erotic, Drama",
        screenShot: require("../assets/images/webSeries/secretOne.jpg"),
        writers: "N/A",
        imdb: "N/A",
        director: "Mohammed Ejaz",
        language: "Hindi (ORG 2.0)",
        story: "Flora’s life turns upside down when she discovers that the epitome of pleasure that she claims to be, fails to satisfy her own partner. And soon she learns that Ankush is having an affair with one of her own students.",
        movieLink: "https://ssrmovies.yachts/secret-ingredient-2023-part-02-complete-hindi-org-ullu-1080p-720p-web-dl-x264/"
    },
    {
        id: 43,
        Image: require("../assets/images/south/liger.jpg"),
        name: "Liger (2022) 1080p 720p 480p WEB-DL x264",
        star: "Mike Tyson, Ananya Panday, Vijay Deverakonda",
        geners: "Action, Drama, Romance",
        screenShot: require("../assets/images/south/ligerOne.jpg"),
        writers: "Puri Jagannadh, Prashant Pandey, A.R. Sreedhar",
        imdb: "3.1/10",
        director: "Puri Jagannadh",
        language: "Hindi (ORG 2.0)",
        story: "A story about martial arts, dreams and star crossed lovers. Liger is an MMA fighter who trains hard and rises up the ranks with one goal in mind, to fight like his idol, world renowned MMA fighter Mark Anderson and get noticed by …",
        movieLink: "https://ssrmovies.yachts/liger-2022-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 44,
        Image: require("../assets/images/webSeries/school.jpg"),
        name: "School Friends (2023) S01 720p 480p WEB-DL x264",
        star: "Meenakshi Chugh, Alisha Parveen, Aaditya Gupta",
        geners: "Comedy, Romance",
        screenShot: require("../assets/images/webSeries/schoolOne.jpg"),
        writers: "N/A",
        imdb: "N/A",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A slice-of-life show that explores the lives of 5 quirky school teenagers who’ve just entered 11th Commerce, as they navigate friendships, heartbreaks, peer pressures, more importantly figuring out who they really want to be. All this in a society that finds it difficult to cope with the fast-changing Gen Z world",
        movieLink: "https://ssrmovies.yachts/school-friends-2023-s01-complete-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 45,
        Image: require("../assets/images/south/spy.jpg"),
        name: "Spy (2023) 1080p 720p 480p WEB-DL x264",
        star: "Nikhil Siddharth, Iswarya Menon, Aryan Rajesh",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/south/spyOne.jpg"),
        writers: "Anirudh Krishna Murthy, K. Raja Shekhar Reddy",
        imdb: "8.3/10",
        director: "Garry Bh",
        language: "Hindi (ORG 2.0)",
        story: "A R&AW agent unravels the connection between a notorious arms dealer and the hidden secrets of Netaji Subhash Chandra Bose, risking everything to protect India from impending chaos",
        movieLink: "https://ssrmovies.yachts/spy-2023-uncut-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 46,
        Image: require("../assets/images/hollywood/dead.jpg"),
        name: "Dead Shot (2023) 1080p 720p 480p WEB-DL x264",
        star: "Aml Ameen, Felicity Jones, Mark Strong",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/hollywood/deadOne.jpg"),
        writers: "Ronan Bennett, Charles Guard, Thomas Guard",
        imdb: "5.6/10",
        director: "Charles Guard, Thomas Guard",
        language: "English (ORG)",
        story: "A retired Irish paramilitary witnesses the fatal shooting of his pregnant wife by an SAS officer. After outwitting the SAS, now wounded, and presumed dead, he escapes, taking his revenge to the dark and paranoid streets of 1970’s …",
        movieLink: "https://ssrmovies.yachts/dead-shot-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 47,
        Image: require("../assets/images/hollywood/ren.jpg"),
        name: "Renfield (2023) 1080p 720p 480p WEB-DL x264",
        star: "Nicholas Hoult, Nicolas Cage, Awkwafina",
        geners: "Comedy, Fantasy, Horror",
        screenShot: require("../assets/images/hollywood/renOne.jpg"),
        writers: "Ryan Ridley, Robert Kirkman",
        imdb: "6.7/10",
        director: "Chris McKay",
        language: "English (ORG)",
        story: "Renfield, Dracula’s henchman and inmate at the lunatic asylum for decades, longs for a life away from the Count, his various demands, and all of the bloodshed that comes with them.",
        movieLink: "https://ssrmovies.yachts/renfield-2023-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 48,
        Image: require("../assets/images/south/malik.jpg"),
        name: "Malikappuram (2022) 1080p 720p 480p WEB-DL x264",
        star: "Unni Mukundan, Alphy Panjikaran, Saiju Kurup",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/malikOne.jpg"),
        writers: "Abhilash Pillai",
        imdb: "8.3/10",
        director: "Vishnu Sasi Shankar",
        language: "Hindi (ORG 2.0)",
        story: "An intense desire of Kallu an 8 year old girl from Panchalimedu village to visit Sabarimala.",
        movieLink: "https://ssrmovies.yachts/malikappuram-2022-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 49,
        Image: require("../assets/images/hollywood/evail.jpg"),
        name: "Evil Dead Rise (2023) 1080p 720p 480p HQ HDCAM x264",
        star: "Alyssa Sutherland, Lily Sullivan, Morgan Davies",
        geners: "Horror",
        screenShot: require("../assets/images/hollywood/evailOne.jpg"),
        writers: "Lee Cronin",
        imdb: "7.5/10",
        director: "Lee Cronin",
        language: "English (ORG)",
        story: " twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
        movieLink: "https://ssrmovies.yachts/evil-dead-rise-2023-dual-audio-hindi-studio-dub-1080p-720p-480p-web-dl-x264/"
    },
    {   
        id: 50,
        Image: require("../assets/images/south/rama.jpg"),
        name: "Rama Banam (2023) V2 1080p 720p 480p HQ DVDScr x264",
        star: "Jagapathi Babu, NassarKushboo",
        geners: "Action, Drama, Family",
        screenShot: require("../assets/images/south/ramaOne.jpg"),
        writers: "Madhusudan Padamati, Bhupathi Raja",
        imdb: "9.7/10",
        director: "Sriwass",
        language: "Hindi (ORG 2.0)",
        story: "Two siblings, who despite their difference in ideologies come together to fight for their common goal",
        movieLink: "https://ssrmovies.yachts/rama-banam-2023-uncut-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 51,
        Image: require("../assets/images/webSeries/wheel.jpg"),
        name: "The Wheel of Time (2023) S02 1080p 720p 480p WEB-DL x264",
        star: "Rosamund Pike, Josha Stradowski, Marcus Rutherford",
        geners: " Action, Adventure, Drama",
        screenShot: require("../assets/images/webSeries/wheelOne.jpg"),
        writers: "Rafe Judkins",
        imdb: "7.1/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Set in a high fantasy world where magic exists, but only some can access it, a woman named Moiraine crosses paths with five young men and women. This sparks a dangerous, world-spanning journey. Based on the book series by Robert Jordan.",
        movieLink: "https://ssrmovies.yachts/the-wheel-of-time-2023-s02-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 52,
        Image: require("../assets/images/bollywood/good.jpg"),
        name: "Good Night (2023) 1080p 720p 480p WEB-DL x264",
        star: "Manikandan K., Bagavathi Perumal, Raichal Rabecca",
        geners: "Comedy, Drama, Romance",
        screenShot: require("../assets/images/bollywood/goodOne.jpg"),
        writers: "Vinayak Chandrasekaran",
        imdb: "8.3/10",
        director: "Vinayak Chandrasekaran",
        language: "Hindi (ORG)",
        story: "A simple boy-next-door character whose biggest problem in life is his snoring.He falls in love with a girl and how the couple overcome his sleeping problem while living together.",
        movieLink: "https://ssrmovies.yachts/good-night-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 53,
        Image: require("../assets/images/hollywood/ghosted.jpg"),
        name: "Ghosted (2023) 1080p 720p 480p WEB-DL x264",
        star: "Ana de Armas, Amy Sedaris, Chris Evans",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/hollywood/ghostedOne.jpg"),
        writers: "Chris McKenna, Rhett Reese, Erik Sommers",
        imdb: "5.8/10",
        director: "Dexter Fletcher",
        language: "English (ORG)",
        story: "Cole falls head over heels for enigmatic Sadie, but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
        movieLink: "https://ssrmovies.yachts/ghosted-2023-hindi-hq-dub-1080p-720p-480p-web-dl-x264/"
    },
    {   
        id: 54,
        Image: require("../assets/images/bollywood/great.jpg"),
        name: "The Great Indian Family (2023) V2 1080p 720p 480p HQ DVDScr x264",
        star: "Vicky Kaushal, Manushi Chhillar, Kumud Mishra",
        geners: "Romance",
        screenShot: require("../assets/images/bollywood/greatOne.jpg"),
        writers: "Vijay Krishna Acharya",
        imdb: "6.4/10",
        director: "Vijay Krishna Acharya",
        language: "Hindi (CAM)",
        story: "Sudden developments send a man’s family into turmoil.",
        movieLink: "https://ssrmovies.yachts/the-great-indian-family-2023/"
    },
    {   
        id: 55,
        Image: require("../assets/images/south/r.jpg"),
        name: "VR (Vikrant Rona) 2022) 1080p 720p 480p WEB-DL x264",
        star: "Sudeep, Nirup Bhandari, Neetha Ashok",
        geners: "Adventure, Drama, Mystery",
        screenShot: require("../assets/images/south/rOne.jpg"),
        writers: "Anup Bhandari, John Mahendran",
        imdb: "8.1/10",
        director: "Anup Bhandari",
        language: "Hindi (ORG 2.0)",
        story: "Almost half a century ago, a remote village in the middle of a tropical rainforest starts witnessing a series of unexplainable events which they attribute to the supernatural.",
        movieLink: "https://ssrmovies.yachts/vr-vikrant-rona-2022-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 56,
        Image: require("../assets/images/hollywood/god.jpg"),
        name: "God Is a Bullet (2023) 1080p 720p 480p WEB-DL x264",
        star: "Maika Monroe, Nikolaj Coster-Waldau, Jamie Foxx",
        geners: "Action, Crime, Horror",
        screenShot: require("../assets/images/hollywood/godOne.jpg"),
        writers: "Writers: Nick Cassavetes, Boston Teran",
        imdb: "6.0/10",
        director: "Nick Cassavetes",
        language: "English (ORG)",
        story: "Taking matters into his own hands, Detective Bob Hightower tries to infiltrate an evil cult to save his kidnapped daughter and avenge the murder of his wife.",
        movieLink: "https://ssrmovies.yachts/god-is-a-bullet-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 57,
        Image: require("../assets/images/south/pop.jpg"),
        name: "Popcorn (2023) 1080p 720p 480p WEB-DL x264",
        star: "Amin, Nithya Das, Avika Gor",
        geners: "Drama",
        screenShot: require("../assets/images/south/popOne.jpg"),
        writers: "Murali Gandham",
        imdb: "4.6/10",
        director: "Murali Gandham",
        language: "Hindi (ORG 2.0)",
        story: "Sameerana and Pavan, who are strangers, meet with an extreme anger on each other will get stuck in a lift . How the emotions unfold beautifully between them and fall in sincere love in 18 hours is the story. From the extreme anger…",
        movieLink: "https://ssrmovies.yachts/popcorn-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 58,
        Image: require("../assets/images/bollywood/haddi.jpg"),
        name: "Haddi (2023) 1080p 720p 480p WEB-DL x264",
        star: "Resh Lamba, Ila Arun, Shriidhar Dubey",
        geners: "Crime, Drama",
        screenShot: require("../assets/images/bollywood/haddiOne.jpg"),
        writers: "Adamya Bhalla, Akshat Ajay Sharma",
        imdb: "N/A/10",
        director: "Akshat Ajay Sharma",
        language: "Hindi (ORG 5.1)",
        story: "A tale of small town boy Hari, who has this desire of becoming a woman, The Story Shows History of Indian Transgenders.",
        movieLink: "https://ssrmovies.yachts/haddi-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 59,
        Image: require("../assets/images/bollywood/lust.jpg"),
        name: "Lust Stories 2 (2023) NF 1080p 720p 480p WEB-DL x264",
        star: "Tamannaah Bhatia, Mrunal Thakur, Kajol",
        geners: "Drama, Romance",
        screenShot: require("../assets/images/bollywood/lustOne.jpg"),
        writers: "N/A",
        imdb: "N/A/10",
        director: "R. Balki, Sujoy Ghosh",
        language: "Hindi (ORG 5.1)",
        story: "Four eminent Indian directors explore sex, desire and love through short films in this sequel to 2018’s Emmy-nominated “Lust Stories”.",
        movieLink: "https://ssrmovies.yachts/lust-stories-2-2023-nf-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 60,
        Image: require("../assets/images/hollywood/meg.jpg"),
        name: "Meg 2: The Trench (2023) 1080p 720p 480p WEB-DL x264",
        star: "Jason Statham, Jing Wu, Shuya Sophia Cai",
        geners: "Action, Adventure, Horror",
        screenShot: require("../assets/images/hollywood/megOne.jpg"),
        writers: "Jon Hoeber, Erich Hoeber, Dean Georgaris",
        imdb: "5.3/10",
        director: "Ben Wheatley",
        language: "English (ORG)",
        story: "A research team encounters multiple threats while exploring the depths of the ocean, including a malevolent mining operation.",
        movieLink: "https://ssrmovies.yachts/meg-2-the-trench-2023-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 61,
        Image: require("../assets/images/bollywood/music.jpg"),
        name: "Music School (2023) 1080p 720p 480p WEB-DL x264",
        star: "Shriya Saran, Sharman Joshi, Prakash Raj",
        geners: "Drama, Musical",
        screenShot: require("../assets/images/bollywood/musicOne.jpg"),
        writers: "Paparao Biyyala, Aripirala Satyaprasad, Shivani Tibrewala",
        imdb: "9.2/10",
        director: "Paparao Biyyala",
        language: "Hindi (ORG 5.1)",
        story: "“Music School” is an eleven song Musical film composed by Ilaiyaraaja. This heart warming and endearing film is about two contemporary and creative teachers, Mary D’Cruz and Manoj who provide a glimpse of the rich culture and refinement of music and theatre to students who are driven by an unimaginative educational system in the name of Math, Science and Technology.",
        movieLink: "https://ssrmovies.yachts/music-school-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 62,
        Image: require("../assets/images/hollywood/hidden.jpg"),
        name: "Hidden Strike (2023) 1080p 720p 480p WEB-DL x264",
        star: "Jackie Chan, John Cena, Pilou Asbaek",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/hollywood/hiddenOne.jpg"),
        writers: "Arash Amel",
        imdb: "5.8/10",
        director: "Scott Waugh",
        language: "English (ORG)",
        story: "Two ex-special forces soldiers must escort a group of civilians along Baghdad’s “Highway of Death” to the safety of the Green Zone.",
        movieLink: "https://ssrmovies.yachts/hidden-strike-2023-nf-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 63,
        Image: require("../assets/images/south/pam.jpg"),
        name: "Pambattam (2023) 1080p 720p 480p HDTV x264",
        star: "Yaashika Aanand, Salil Ankola, Jeevan",
        geners: "Thriller",
        screenShot: require("../assets/images/south/pamOne.jpg"),
        writers: "V C.Vadivudaiyan",
        imdb: "N/A/10",
        director: "V.C. Vadivudaiyan",
        language: "Hindi (ORG 2.0)",
        story: "Pambattam is an Indian movie directed by V.C. Vadivudaiyan starring Jeevan, Mallika Sherawat, Suman Talwar and Rittika Sen. The feature film is produced by V.Palanivel and the music composed by Amrish.",
        movieLink: "https://ssrmovies.yachts/pambattam-2023-hindi-org-2-0-1080p-720p-480p-hdtv-x264/"
    },
    {   
        id: 64,
        Image: require("../assets/images/south/pizza.jpg"),
        name: "Pizza 3: The Mummy (2023) 1080p 720p 480p WEB-DL x264",
        star: "Kavitha Bharathi, Raveena Daha, Ashwin Kakumanu",
        geners: "Drama, Horror, Thriller",
        screenShot: require("../assets/images/south/pizzaOne.jpg"),
        writers: "Mohan Govind",
        imdb: "4.7/10",
        director: "Mohan Govind",
        language: "Hindi (ORG 2.0)",
        story: "The protagonist on a probe to solve a series of murders that take place exactly where he delivers food.",
        movieLink: "https://ssrmovies.yachts/pizza-3-the-mummy-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 65,
        Image: require("../assets/images/hollywood/knight.jpg"),
        name: "Knights of the Zodiac (2023) 1080p 720p 480p BluRay x264",
        star: "Mackenyu, Famke Janssen, Madison Iseman",
        geners: "Action, Adventure, Drama",
        screenShot: require("../assets/images/hollywood/knightOne.jpg"),
        writers: "Josh Campbell, Matt Stuecken, Kiel Murray",
        imdb: "4.6/10",
        director: "Tomasz Baginski",
        language: "English (ORG)",
        story: "When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers that he is destined to protect her and save the world. But only if he can face his own past and become a Knight of the Zodiac.",
        movieLink: "https://ssrmovies.yachts/knights-of-the-zodiac-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 66,
        Image: require("../assets/images/south/mavareen.jpg"),
        name: "Maaveeran (2023) 1080p 720p 480p WEB-DL x264",
        star: "Sivakarthikeyan, Aditi Shankar, Mysskin",
        geners: "Action, Drama, Thriller",
        screenShot: require("../assets/images/south/mavareenOne.jpg"),
        writers: "Madonne Ashwin",
        imdb: "7.6/10",
        director: "Madonne Ashwin",
        language: "Hindi (ORG 2.0)",
        story: "A cowardly cartoonist starts being ‘controlled’ by a cartoon action figure, and takes on a corrupt politician.",
        movieLink: "https://ssrmovies.yachts/maaveeran-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 67,
        Image: require("../assets/images/hollywood/mission.jpg"),
        name: "Mission: Impossible – Dead Reckoning Part One (2023) 1080p 720p 480p HDTC x264",
        star: "Tom Cruise, Hayley Atwell, Ving Rhames",
        geners: "Action, Adventure, Thriller",
        screenShot: require("../assets/images/hollywood/missionOne.jpg"),
        writers: "Bruce Geller, Erik Jendresen, Christopher McQuarrie",
        imdb: "8.1/10",
        director: "Christopher McQuarrie",
        language: "English (ORG)",
        story: "Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.",
        movieLink: "https://ssrmovies.yachts/mission-impossible-dead-reckoning-part-one-2023-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 68,
        Image: require("../assets/images/south/michal.jpg"),
        name: "Michael (2023) 1080p 720p 480p WEB-DL x264",
        star: "Vijay Sethupathi, Sundeep Kishan, Varalaxmi Sarathkumar",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/michalOne.jpg"),
        writers: "Ranjit Jeyakodi",
        imdb: "5.8/10",
        director: "Ranjit Jeyakodi",
        language: "Hindi (ORG 2.0)",
        story: "The gang fighting over places. A youngster decides to gain control of the area. Can he complete his dream of ruling over the place?",
        movieLink: "https://ssrmovies.yachts/michael-2023-uncut-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 69,
        Image: require("../assets/images/south/o.jpg"),
        name: "O Saathiya (2023) 1080p 720p 480p WEB-DL x264",
        star: "Aryan Gowra, Mishti Chakravarty, Kalpalatha",
        geners: "Comedy, Musical, Romance",
        screenShot: require("../assets/images/south/oOne.jpg"),
        writers: "Deepu, Aryan Gowra",
        imdb: "8.2/10",
        director: "Divya Bhavna",
        language: "Hindi (ORG 2.0)",
        story: "The evolving love story of Arjun and Keerthi and the trials and tribulations they face as they mature from adolescence to adulthood.",
        movieLink: "https://ssrmovies.yachts/o-saathiya-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
];

export default AllCategories;