const BollywoodDetails = [
    {   
        id: 1,
        Image: require("../assets/images/bollywood/afwah.jpg"),
        name: "Afwaah 1080p 720p 480p WEB-DL x264",
        star: "Bhumi Pednekar, Nawazuddin Siddiqui, Sumeet Vyas",
        geners: "Drama, Thriller",
        screenShot: require("../assets/images/bollywood/afwahOne.jpg"),
        writers: "Apurva Dhar Badgaiyan, Shiva Shankar Bajpai, Nisarg Mehta",
        imdb: "4.9/10",
        director: "Sudhir Mishra",
        language: "Hindi(ORG 5.1)",
        story: "An advertising professional and a political heiress whose lives are upended by a viral social media rumour.",
        movieLink: "https://ssrmovies.yachts/afwaah-2023-nf-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 2,
        Image: require("../assets/images/bollywood/ajmer.jpg"),
        name: "Ajmer 92 1080p 720p 480p WEB-DL x264",
        star: "Alka Amin, Mahesh Balraj, Aakash Dahiya",
        geners: "Drama",
        screenShot: require("../assets/images/bollywood/ajmerOne.jpg"),
        writers: "Suraj Pal Rajak, Gyanendra Pratap Singh, Pushpendra Singh",
        imdb: " 8.9/10",
        director: "Pushpendra Singh",
        language: "Hindi (CAM)",
        story: "A heart-wrenching story of 250 girls from Ajmer. Ajmer 92 releasing in cinemas on 14th July.",
        movieName: "https://ssrmovies.yachts/ajmer-92-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {   
        id: 3,
        Image: require("../assets/images/bollywood/akelli.jpg"),
        name: "Akelli (2023) 1080p 720p 480p WEB-DL x264",
        star: "Nushrratt Bharuccha, Tsahi Halevi, Amir Boutrous",
        geners: "Drama, Thriller",
        screenShot: require("../assets/images/bollywood/akelliOne.jpg"),
        writers: "Pranay Meshram, Gunjan Saxena, Ayush Tiwari",
        imdb: "N/A/10",
        director: "Pranay Meshram",
        language: "Hindi (CAM)",
        story: "A middle class girl Jyoti. Who deals with financial issues. The story shows how Jyoti tackle those obstacles.",
        movieLink: "https://ssrmovies.yachts/akelli-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {   
        id: 4,
        Image: require("../assets/images/bollywood/bawal.jpg"),
        name: "Bawaal (2023) 1080p 720p 480p WEB-DL x264",
        star: "Varun Dhawan, Janhvi Kapoor, Parth Siddhpura",
        geners: "Action, Drama, Romance",
        screenShot: require("../assets/images/bollywood/bawalOne.jpg"),
        writers: "Piyush Gupta, Shreyas Jain, Nikhil Mehrotra",
        imdb: "N/A/10",
        director: "Nitesh Tiwari",
        language: "Hindi (ORG 5.1)",
        story: "A small-town man who falls in love with the most beautiful girl in town. He wants to marry her one day because marrying her can rise up his social position.",
        movieLink: "https://ssrmovies.yachts/?s=Bawaal"
    },
    {   
        id: 5,
        Image: require("../assets/images/bollywood/blind.jpg"),
        name: "Blind (2023) 1080p 720p 480p WEB-DL x264",
        star: "Sonam Kapoor, Lucy Aarden, Lillete Dubey",
        geners: "Crime, Drama, Thriller",
        screenShot: require("../assets/images/bollywood/blindOne.jpg"),
        writers: "Shome MakhijaSudeep Nigam",
        imdb: "N/A",
        director: "Shome Makhija",
        language: "Hindi (ORG 5.1)",
        story: "When a twist of fate leaves Gia blind, she must summon every ounce of courage to rebuild her life. But when she becomes the sole witness to a heinous crime, she unwittingly enters a deadly game of cat and mouse with a dangerous criminal.",
        movieLink: "https://ssrmovies.yachts/blind-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 6,
        Image: require("../assets/images/bollywood/farhana.jpg"),
        name: "Farhana (2023) 1080p 720p 480p WEB-DL x264",
        star: "Aishwarya Rajesh, K. Selvaraghavan, Anumol K. Manoharan",
        geners: "Drama, Thriller",
        screenShot: require("../assets/images/bollywood/farhanaOne.jpg"),
        writers: "Sankar Dass, Renjith Ravindran, Nelson Venkatesan",
        imdb: "5.9/10 ",
        director: "Nelson Venkatesan",
        language: "Hindi (ORG)",
        story: "A middle-class mother takes a call centre job due to her financial reasons, and that gives her freedom, but it leads into a web of dangers.",
        movieLink: "https://ssrmovies.yachts/farhana-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 7,
        Image: require("../assets/images/bollywood/firangi.jpg"),
        name: "Firangi (2017) 1080p 720p 480p WEB-DL x264",
        star: "Kapil Sharma, Ishita Dutta, Monica Gill",
        geners: "Comedy, Drama",
        screenShot: require("../assets/images/bollywood/firangiOne.jpg"),
        writers: "Rupinder Chahal, Rajesh Chawla, Rajiv Dhingra",
        imdb: "4.3/10",
        director: "Rajiv Dhingra",
        language: "Hindi (ORG)",
        story: "Manga, an unemployed young man from village Behrampur, was born with a healing gift through which he could cure anyone’s backache. This unique ability of his helps him get the job of Orderly from British Officer Mark Daniels. During a visit to village Naku Guda for his friend Heera’s wedding, Manga comes across Sargi and falls in love with her. Manga’s parents visit Sargi’s house with a marriage proposal but Lalaji, Sargi’s grandfather, who is not happy with Manga working for the Britishers, refuses the proposal.",
        movieLink: "https://ssrmovies.yachts/firangi-2017-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 8,
        Image: require("../assets/images/bollywood/gadar.jpg"),
        name: "Gadar 2 (2023) V2 1080p 720p 480p HDTS x264",
        star: "Sunny Deol, Ameesha Patel, Utkarsh Sharma",
        geners: "Action, Drama",
        screenShot: require("../assets/images/bollywood/gadarOne.jpg"),
        writers: "Shaktimaan Talwar",
        imdb: "7.2/10",
        director: "Anil Sharma",
        language: "Hindi (CAM)",
        story: "India’s most loved family of Tara, Sakeena and Jeete; 22 years after its predecessor. Set against the Indo-Pakistan war of 1971, Tara Singh, once again, will face every enemy to protect the honor of country and family.",
        movieLink: "https://ssrmovies.yachts/gadar-2-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 9,
        Image: require("../assets/images/bollywood/ghoomer.jpg"),
        name: "Ghoomer (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Amitabh Bachchan, Shabana Azmi, Abhishek Bachchan",
        geners: "Drama, Sport",
        screenShot: require("../assets/images/bollywood/ghoomerOne.jpg"),
        writers: "R. Balki, Rahul Sengupta, Rishi Virmani",
        imdb: "9.7/10",
        director: "R.Balki",
        language: "Hindi (CAM)",
        story: "Inspired by the incredible achievement of Karoly Takacs, follow the achievements of special athletes, and who have achieved more than when they were called “normal”.",
        movieLink: "https://ssrmovies.yachts/ghoomer-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {   
        id: 10,
        Image: require("../assets/images/bollywood/good.jpg"),
        name: "Good Night (2023) 1080p 720p 480p WEB-DL x264",
        star: "Manikandan K., Bagavathi Perumal, Raichal Rabecca",
        geners: "Comedy, Drama, Romance",
        screenShot: require("../assets/images/bollywood/goodOne.jpg"),
        writers: "Vinayak Chandrasekaran",
        imdb: "8.3/10",
        director: "Vinayak Chandrasekaran",
        language: "Hindi (ORG)",
        story: "A simple boy-next-door character whose biggest problem in life is his snoring.He falls in love with a girl and how the couple overcome his sleeping problem while living together.",
        movieLink: "https://ssrmovies.yachts/good-night-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 11,
        Image: require("../assets/images/bollywood/great.jpg"),
        name: "The Great Indian Family (2023) V2 1080p 720p 480p HQ DVDScr x264",
        star: "Vicky Kaushal, Manushi Chhillar, Kumud Mishra",
        geners: "Romance",
        screenShot: require("../assets/images/bollywood/greatOne.jpg"),
        writers: "Vijay Krishna Acharya",
        imdb: "6.4/10",
        director: "Vijay Krishna Acharya",
        language: "Hindi (CAM)",
        story: "Sudden developments send a man’s family into turmoil.",
        movieLink: "https://ssrmovies.yachts/the-great-indian-family-2023/"
    },
    {   
        id: 12,
        Image: require("../assets/images/bollywood/haddi.jpg"),
        name: "Haddi (2023) 1080p 720p 480p WEB-DL x264",
        star: "Resh Lamba, Ila Arun, Shriidhar Dubey",
        geners: "Crime, Drama",
        screenShot: require("../assets/images/bollywood/haddiOne.jpg"),
        writers: "Adamya Bhalla, Akshat Ajay Sharma",
        imdb: "N/A/10",
        director: "Akshat Ajay Sharma",
        language: "Hindi (ORG 5.1)",
        story: "A tale of small town boy Hari, who has this desire of becoming a woman, The Story Shows History of Indian Transgenders.",
        movieLink: "https://ssrmovies.yachts/haddi-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 13,
        Image: require("../assets/images/bollywood/hate.jpg"),
        name: "O Pushpa I Hate Tears (2020) 1080p 720p 480p WEB-DL x264",
        star: "Krishna Abhishek, Karthik Jayaram, Arjumman Mughal",
        geners: "Comedy, Thriller",
        screenShot: require("../assets/images/bollywood/hateOne.jpg"),
        writers: "Aadesh K. Arjun",
        imdb: "4.8/10",
        director: "Dinkar Kapoor",
        language: "Hindi (ORG)",
        story: "You always fall in love with those whom you want to be the part of your life. This is the only truth and only condition. When Aditya fallen in love with Pushpa, she thought that he only loves her. But she gets traumatized when she came to know that Aditya was in love with her only to get her money. He only wants money not Pushpa. Aditya wants Pushpa out of his way, so he takes the help of Shyam. But Shyam smartly get Pushpa in love with him and also get a hold on her.",
        movieLink: "https://ssrmovies.yachts/o-pushpa-i-hate-tears-2020-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 14,
        Image: require("../assets/images/bollywood/jawan.jpg"),
        name: "Jawan (2023) V2 1080p 720p 480p HQ DVDScr x264",
        star: "Shah Rukh Khan, Nayanthara, Vijay Sethupathi",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/bollywood/jawanOne.jpg"),
        writers: "Sumit Arora, Atlee, Ramanagirivasan",
        imdb: "8.3/10",
        director: "Atlee",
        language: "Tamil (CAM) + Telugu (CAM) + Hindi (CAM)",
        story: "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
        movieLink: "https://ssrmovies.yachts/jawan-2023/"
    },
    {   
        id: 15,
        Image: require("../assets/images/bollywood/kutch.jpg"),
        name: "Kutch Express (2023) 1080p 720p 480p WEB-DL x264",
        star: "Ratna Pathak Shah, Manasi Parekh, Dharmendra Gohil",
        geners: "Drama, Family",
        screenShot: require("../assets/images/bollywood/kutchOne.jpg"),
        writers: "Karan Bhanushali, Rahul Mallick, Raam Mori",
        imdb: "6.6/10",
        director: "Viral Shah",
        language: "Hindi (ORG)",
        story: "Revolves around how the journey of a thousand miles begins with a single step and explores love and life.",
        movieLink: "https://ssrmovies.yachts/kutch-express-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 16,
        Image: require("../assets/images/bollywood/love.jpg"),
        name: "Love-All (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "KaSporty Kay Menon, Swastika Mukherjee, Shriswara",
        geners: "",
        screenShot: require("../assets/images/bollywood/loveOne.jpg"),
        writers: "Sudhanshu Sharma",
        imdb: "8.3/10",
        director: "Sudhanshu Sharma",
        language: "Hindi (CAM)",
        story: "Story of Siddharth, a small-city boy, begins at a dilapidated Railways quarter granted to his mother, after his father’s death, as one of the few perks associated with a railway job. Siddharth, though not living a life with even moderate means, finds it exciting being a promising Badminton player with all sports-lover in the city looking at him as a future champion.",
        movieLink: "https://ssrmovies.yachts/love-all-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {   
        id: 17,
        Image: require("../assets/images/bollywood/lust.jpg"),
        name: "Lust Stories 2 (2023) NF 1080p 720p 480p WEB-DL x264",
        star: "Tamannaah Bhatia, Mrunal Thakur, Kajol",
        geners: "Drama, Romance",
        screenShot: require("../assets/images/bollywood/lustOne.jpg"),
        writers: "N/A",
        imdb: "N/A/10",
        director: "R. Balki, Sujoy Ghosh",
        language: "Hindi (ORG 5.1)",
        story: "Four eminent Indian directors explore sex, desire and love through short films in this sequel to 2018’s Emmy-nominated “Lust Stories”.",
        movieLink: "https://ssrmovies.yachts/lust-stories-2-2023-nf-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 18,
        Image: require("../assets/images/bollywood/minus.jpg"),
        name: "Minus 31-The Nagpur Files (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Raghubir Yadav, Shivankit Singh Parihar, Rajesh Sharma",
        geners: "Crime",
        screenShot: require("../assets/images/bollywood/minusOne.jpg"),
        writers: "Charulata Maitra, Ankit Bhuptani, Pratik Moitro",
        imdb: "8.9/10",
        director: "Pratik Moitro",
        language: "Hindi (ORG 5.1)",
        story: "A murder has happened at the time of COVID, and the female cop is on duty to find the murderer.",
        movieLink: "https://ssrmovies.yachts/minus-31-the-nagpur-files-2023-hindi-1080p-720p-480p-hq-dvdscr-x264/"
    },
    {   
        id: 19,
        Image: require("../assets/images/bollywood/nine.jpg"),
        name: "1920: Horrors of the Heart (2023) 1080p 720p 480p WEB-DL x264",
        star: "Rupam Bag, Amit Behl, Barkha Bisht",
        geners: "Drama, Horror",
        screenShot: require("../assets/images/bollywood/nineOne.jpg"),
        writers: "Mahesh Bhatt, Shweta Bothra, Suhrita Das",
        imdb: "3.6/10",
        director: "Krishna Bhatt",
        language: "Hindi (ORG 5.1)",
        story: "A young girl walks into a world of darkness is search of revenge but darkness consumes her making her a victim of that very revenge.",
        movieLink: "https://ssrmovies.yachts/1920-horrors-of-the-heart-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 20,
        Image: require("../assets/images/bollywood/music.jpg"),
        name: "Music School (2023) 1080p 720p 480p WEB-DL x264",
        star: "Shriya Saran, Sharman Joshi, Prakash Raj",
        geners: "Drama, Musical",
        screenShot: require("../assets/images/bollywood/musicOne.jpg"),
        writers: "Paparao Biyyala, Aripirala Satyaprasad, Shivani Tibrewala",
        imdb: "9.2/10",
        director: "Paparao Biyyala",
        language: "Hindi (ORG 5.1)",
        story: "“Music School” is an eleven song Musical film composed by Ilaiyaraaja. This heart warming and endearing film is about two contemporary and creative teachers, Mary D’Cruz and Manoj who provide a glimpse of the rich culture and refinement of music and theatre to students who are driven by an unimaginative educational system in the name of Math, Science and Technology.",
        movieLink: "https://ssrmovies.yachts/music-school-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    }
];

export default BollywoodDetails;