const HollywoodDetails = [
    {   
        id: 1,
        Image: require("../assets/images/hollywood/barbie.jpg"),
        name: "Barbie (2023) 1080p 720p 480p HC WEB-DL x264",
        star: "Margot Robbie, Ryan Gosling, Issa Rae",
        geners: "Adventure, Comedy, Fantasy",
        screenShot: require("../assets/images/hollywood/barbieOne.jpg"),
        writers: "Greta Gerwig, Noah Baumbach",
        imdb: "7.4/10",
        director: "Greta Gerwig",
        language: "English (ORG)",
        story: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        movieLink: "https://ssrmovies.yachts/barbie-2023-english-1080p-720p-480p-hdts-x264/"
    },
    {   
        id: 2,
        Image: require("../assets/images/hollywood/best.jpg"),
        name: "The Best Man (2023) 1080p 720p 480p WEB-DL x264",
        star: "Brendan Fehr, Nicky Whelan, Scout Taylor-Compton",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/hollywood/bestOne.jpg"),
        writers: "C. Alec Rossel, Shane Dax Taylor, Daniel Zirilli",
        imdb: "4.1/10",
        director: "Shane Dax Taylor",
        language: "English (ORG)",
        story: "Mercenaries seize control of a remote resort hotel during a wedding and it’s up to the best man, the groom and their drunken best friend to stop the terrorists and save the hostages.",
        movieLink: "https://ssrmovies.yachts/the-best-man-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 3,
        Image: require("../assets/images/hollywood/big.jpg"),
        name: "Big George Foreman (2023) 1080p 720p 480p BluRay x264",
        star: "Khris Davis, Jasmine Mathews, Sullivan Jones",
        geners: "Biography, Drama, Sport",
        screenShot: require("../assets/images/hollywood/bigOne.jpg"),
        writers: "Frank Baldwin, George Tillman Jr., Dan Gordon",
        imdb: "6.5/10",
        director: "George Tillman Jr.",
        language: "English (ORG)",
        story: "Follow the remarkable life and times of Foreman, from Olympic Gold medalist to World Heavyweight champion, the Rumble in the Jungle fight with Muhammad Ali in Zaire, to finding his faith, retiring, and becoming a preacher. When financial hardship hits his family and church, he steps back in the ring and regains the championship at age 45, becoming the oldest heavyweight champion in boxing history.",
        movieLink: "https://ssrmovies.yachts/big-george-foreman-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 4,
        Image: require("../assets/images/hollywood/bital.jpg"),
        name: "Blue Beetle (2023) 1080p 720p 480p WEB-DL x264",
        star: "Xolo Maridueña, Bruna Marquezine, Becky G",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/hollywood/bitalOne.jpg"),
        writers: "Gareth Dunnet-Alcocer",
        imdb: "6.7/10",
        director: "Angel Manuel Soto",
        language: "English (ORG)",
        story: "An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor that’s capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blu…",
        movieLink: "https://ssrmovies.yachts/blue-beetle-2023-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 5,
        Image: require("../assets/images/hollywood/black.jpg"),
        name: "The Black Demon (2023) 1080p 720p 480p BluRay x264",
        star: "Omar Chaparro, Bolivar Sanchez, Carlos Solórzano",
        geners: "Horror, Sci-Fi, Thriller",
        screenShot: require("../assets/images/hollywood/blackOne.jpg"),
        writers: "Carlos Cisco, Boise Esquerra",
        imdb: "3.7/10",
        director: "Adrian Grunberg",
        language: "English (ORG)",
        story: "tranded on a crumbling rig in Baja, a family faces off against a vengeful megalodon shark.",
        movieLink: "https://ssrmovies.yachts/the-black-demon-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 6,
        Image: require("../assets/images/hollywood/covenent.jpg"),
        name: "The Covenant (2023) 1080p 720p 480p BluRay x264",
        star: "Jake Gyllenhaal, Dar Salim, Sean Sagar",
        geners: "Action, Thriller, War",
        screenShot: require("../assets/images/hollywood/covenentOne.jpg"),
        writers: "Guy Ritchie, Ivan Atkinson, Marn Davies",
        imdb: "7.5/10",
        director: "Guy Ritchie",
        language: "English (ORG)",
        story: "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
        movieLink: "https://ssrmovies.yachts/the-covenant-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 7,
        Image: require("../assets/images/hollywood/crater.jpg"),
        name: "Crater (2023) 1080p 720p 480p WEB-DL x264",
        star: "Mckenna Grace, Brady Noon, Billy Barratt",
        geners: "Adventure, Drama, Family",
        screenShot: require("../assets/images/hollywood/craterOne.jpg"),
        writers: "John Griffin",
        imdb: "4.7/10",
        director: "Kyle Patrick Alvarez",
        language: "English (ORG)",
        story: "After the death of his father, a boy growing up on a lunar mining colony takes a trip to explore a legendary crater, along with his four best friends, prior to being permanently relocated to another planet.",
        movieLink: "https://ssrmovies.yachts/crater-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 8,
        Image: require("../assets/images/hollywood/dead.jpg"),
        name: "Dead Shot (2023) 1080p 720p 480p WEB-DL x264",
        star: "Aml Ameen, Felicity Jones, Mark Strong",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/hollywood/deadOne.jpg"),
        writers: "Ronan Bennett, Charles Guard, Thomas Guard",
        imdb: "5.6/10",
        director: "Charles Guard, Thomas Guard",
        language: "English (ORG)",
        story: "A retired Irish paramilitary witnesses the fatal shooting of his pregnant wife by an SAS officer. After outwitting the SAS, now wounded, and presumed dead, he escapes, taking his revenge to the dark and paranoid streets of 1970’s …",
        movieLink: "https://ssrmovies.yachts/dead-shot-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 9,
        Image: require("../assets/images/hollywood/evail.jpg"),
        name: "Evil Dead Rise (2023) 1080p 720p 480p HQ HDCAM x264",
        star: "Alyssa Sutherland, Lily Sullivan, Morgan Davies",
        geners: "Horror",
        screenShot: require("../assets/images/hollywood/evailOne.jpg"),
        writers: "Lee Cronin",
        imdb: "7.5/10",
        director: "Lee Cronin",
        language: "English (ORG)",
        story: " twisted tale of two estranged sisters whose reunion is cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
        movieLink: "https://ssrmovies.yachts/evil-dead-rise-2023-dual-audio-hindi-studio-dub-1080p-720p-480p-web-dl-x264/"
    },
    {   
        id: 10,
        Image: require("../assets/images/hollywood/galaxy.jpg"),
        name: "Guardians of the Galaxy Vol. 3 (2023) 1080p 720p 480p WEB-DL x264",
        star: "Chris Pratt, Chukwudi Iwuji, Bradley Cooper",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/hollywood/galaxyOne.jpg"),
        writers: "James Gunn, Jim Starlin, Stan Lee",
        imdb: "8.1/10",
        director: "James Gunn",
        language: "English (ORG)",
        story: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own – a mission that could mean the end of the Guardians if not successful.",
        movieLink: "https://ssrmovies.yachts/guardians-of-the-galaxy-vol-3-2023-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 11,
        Image: require("../assets/images/hollywood/ghosted.jpg"),
        name: "Ghosted (2023) 1080p 720p 480p WEB-DL x264",
        star: "Ana de Armas, Amy Sedaris, Chris Evans",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/hollywood/ghostedOne.jpg"),
        writers: "Chris McKenna, Rhett Reese, Erik Sommers",
        imdb: "5.8/10",
        director: "Dexter Fletcher",
        language: "English (ORG)",
        story: "Cole falls head over heels for enigmatic Sadie, but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
        movieLink: "https://ssrmovies.yachts/ghosted-2023-hindi-hq-dub-1080p-720p-480p-web-dl-x264/"
    },
    {   
        id: 12,
        Image: require("../assets/images/hollywood/god.jpg"),
        name: "God Is a Bullet (2023) 1080p 720p 480p WEB-DL x264",
        star: "Maika Monroe, Nikolaj Coster-Waldau, Jamie Foxx",
        geners: "Action, Crime, Horror",
        screenShot: require("../assets/images/hollywood/godOne.jpg"),
        writers: "Writers: Nick Cassavetes, Boston Teran",
        imdb: "6.0/10",
        director: "Nick Cassavetes",
        language: "English (ORG)",
        story: "Taking matters into his own hands, Detective Bob Hightower tries to infiltrate an evil cult to save his kidnapped daughter and avenge the murder of his wife.",
        movieLink: "https://ssrmovies.yachts/god-is-a-bullet-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 13,
        Image: require("../assets/images/hollywood/hidden.jpg"),
        name: "Hidden Strike (2023) 1080p 720p 480p WEB-DL x264",
        star: "Jackie Chan, John Cena, Pilou Asbaek",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/hollywood/hiddenOne.jpg"),
        writers: "Arash Amel",
        imdb: "5.8/10",
        director: "Scott Waugh",
        language: "English (ORG)",
        story: "Two ex-special forces soldiers must escort a group of civilians along Baghdad’s “Highway of Death” to the safety of the Green Zone.",
        movieLink: "https://ssrmovies.yachts/hidden-strike-2023-nf-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 14,
        Image: require("../assets/images/hollywood/insidious.jpg"),
        name: "Insidious: The Red Door (2023) 1080p 720p 480p WEB-DL x264",
        star: "Ty Simpkins, Patrick Wilson, Rose Byrne",
        geners: "Horror, Mystery, Thriller",
        screenShot: require("../assets/images/hollywood/insidiousOne.jpg"),
        writers: "Leigh Whannell, Scott Teems",
        imdb: "6.0/10",
        director: "Patrick Wilson",
        language: "English (ORG)",
        story: "The Lamberts must go deeper into The Further than ever before to put their demons to rest once and for all.",
        movieLink: "https://ssrmovies.yachts/insidious-the-red-door-2023-amzn-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 15,
        Image: require("../assets/images/hollywood/knight.jpg"),
        name: "Knights of the Zodiac (2023) 1080p 720p 480p BluRay x264",
        star: "Mackenyu, Famke Janssen, Madison Iseman",
        geners: "Action, Adventure, Drama",
        screenShot: require("../assets/images/hollywood/knightOne.jpg"),
        writers: "Josh Campbell, Matt Stuecken, Kiel Murray",
        imdb: "4.6/10",
        director: "Tomasz Baginski",
        language: "English (ORG)",
        story: "When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers that he is destined to protect her and save the world. But only if he can face his own past and become a Knight of the Zodiac.",
        movieLink: "https://ssrmovies.yachts/knights-of-the-zodiac-2023-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {   
        id: 16,
        Image: require("../assets/images/hollywood/last.jpg"),
        name: "Last Sentinel (2023) 1080p 720p 480p WEB-DL x264",
        star: "Kate Bosworth, Martin McCann, Thomas Kretschmann",
        geners: "Drama, Sci-Fi, Thriller",
        screenShot: require("../assets/images/hollywood/lastOne.jpg"),
        writers: "Malachi Smyth",
        imdb: "6.7/10",
        director: "Tanel Toom",
        language: "English (ORG)",
        story: "A squad of soldiers is stranded on an abandoned military base on a near future Earth waiting for the relief or the enemy, whichever comes first.",
        movieLink: "https://ssrmovies.yachts/last-sentinel-2023-english-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 17,
        Image: require("../assets/images/hollywood/meg.jpg"),
        name: "Meg 2: The Trench (2023) 1080p 720p 480p WEB-DL x264",
        star: "Jason Statham, Jing Wu, Shuya Sophia Cai",
        geners: "Action, Adventure, Horror",
        screenShot: require("../assets/images/hollywood/megOne.jpg"),
        writers: "Jon Hoeber, Erich Hoeber, Dean Georgaris",
        imdb: "5.3/10",
        director: "Ben Wheatley",
        language: "English (ORG)",
        story: "A research team encounters multiple threats while exploring the depths of the ocean, including a malevolent mining operation.",
        movieLink: "https://ssrmovies.yachts/meg-2-the-trench-2023-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 18,
        Image: require("../assets/images/hollywood/mission.jpg"),
        name: "Mission: Impossible – Dead Reckoning Part One (2023) 1080p 720p 480p HDTC x264",
        star: "Tom Cruise, Hayley Atwell, Ving Rhames",
        geners: "Action, Adventure, Thriller",
        screenShot: require("../assets/images/hollywood/missionOne.jpg"),
        writers: "Bruce Geller, Erik Jendresen, Christopher McQuarrie",
        imdb: "8.1/10",
        director: "Christopher McQuarrie",
        language: "English (ORG)",
        story: "Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.",
        movieLink: "https://ssrmovies.yachts/mission-impossible-dead-reckoning-part-one-2023-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 19,
        Image: require("../assets/images/hollywood/one.jpg"),
        name: "One Piece (2023) S01 NF 720p 480p WEB-DL x264",
        star: "Iñaki Godoy, Mackenyu, Emily Rudd",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/hollywood/oneOne.jpg"),
        writers: "Steven Maeda, Matt Owens",
        imdb: "8.7/10",
        director: "N/A",
        language: "English (ORG)",
        story: "In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as ‘One Piece.’",
        movieLink: "https://ssrmovies.yachts/one-piece-2023-s01-complete-nf-dual-audio-hindi-org-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 20,
        Image: require("../assets/images/hollywood/ren.jpg"),
        name: "Renfield (2023) 1080p 720p 480p WEB-DL x264",
        star: "Nicholas Hoult, Nicolas Cage, Awkwafina",
        geners: "Comedy, Fantasy, Horror",
        screenShot: require("../assets/images/hollywood/renOne.jpg"),
        writers: "Ryan Ridley, Robert Kirkman",
        imdb: "6.7/10",
        director: "Chris McKay",
        language: "English (ORG)",
        story: "Renfield, Dracula’s henchman and inmate at the lunatic asylum for decades, longs for a life away from the Count, his various demands, and all of the bloodshed that comes with them.",
        movieLink: "https://ssrmovies.yachts/renfield-2023-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
];

export default HollywoodDetails;