const Marvel = [
    {
        id: 1,
        Image: require("../assets/images/marvel/iron.jpg"),
        name: "Iron Man (2008) 1080p 720p 480p BluRay x264",
        star: "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/ironOne.jpg"),
        writers: "Mark Fergus, Hawk Ostby, Art Marcum",
        imdb: "7.9/10",
        director: "Jon Favreau",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he’s given a ride on enemy lines. That ride ends badly when Stark’s Humvee that he’s riding in is attacked by enemy combatants. He survives – barely – with a chest full of shrapnel and a car battery attached to his heart.",
        movieLink: "https://ssrmovies.yachts/iron-man-2008-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {
        id: 2,
        Image: require("../assets/images/marvel/ironTwo.jpg"),
        name: "Iron Man 2 (2010) 1080p 720p 480p BluRay x264",
        star: "Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/ironTwoOne.jpg"),
        writers: "Justin Theroux, Stan Lee, Don Heck",
        imdb: "6.9/10",
        director: "Jon Favreau",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press, and the public to share his technology with the military. Unwilling to let go of his invention, Stark, along with Pepper Potts, and James “Rhodey” Rhodes at his side, must forge new alliances – and confront powerful enemies.",
        movieLink: "https://ssrmovies.yachts/iron-man-2-2010-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {
        id: 3,
        Image: require("../assets/images/marvel/ironThree.jpg"),
        name: "Iron Man 3 (2013) 1080p 720p 480p BluRay x264",
        star: "Robert Downey Jr., Guy Pearce, Gwyneth Paltrow",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/ironThreeOne.jpg"),
        writers: "Drew Pearce, Shane Black, Stan Lee",
        imdb: "7.1/10",
        director: "Shane Black",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Marvel’s “Iron Man 3” pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy’s hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man?",
        movieLink: "https://ssrmovies.yachts/iron-man-3-2013-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {
        id: 4,
        Image: require("../assets/images/marvel/seeHulk.jpg"),
        name: "She-Hulk: Attorney at Law (2022) S01 1080p 720p 480p WEB-DL x264",
        star: "Tatiana Maslany, Mark Ruffalo, Charlie Cox",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/marvel/seeHulkOne.jpg"),
        writers: "Jessica Gao",
        imdb: "4.8/10",
        director: "N/A",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered Hulk.",
        movieLink: "https://ssrmovies.yachts/she-hulk-attorney-at-law-2022-s01-complete-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 5,
        Image: require("../assets/images/marvel/hulk.jpg"),
        name: "Hulk (2003) 480p BluRay x264",
        star: "Eric Bana, Jennifer Connelly, Sam Elliott, Josh Lucas",
        geners: "Action, Sci-Fi",
        screenShot: require("../assets/images/marvel/hulkOne.jpg"),
        writers: "Stan Lee, Jack Kirby, James Schamus",
        imdb: "5.6/10",
        director: "Ang Lee",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Bruce Banner, a brilliant scientist with a cloudy past about his family, is involved in an accident in his laboratory causing him to become exposed to gamma radiation and Nanomeds (A tiny life-form that is supposed to heal wounds but has killed everything with which they have made contact). Confused and curious about his survival, Banner discovers that since the accident, whenever he becomes angry he transforms into a giant green monster destroying everything in sight in an act of fury.",
        movieLink: "https://ssrmovies.yachts/hulk-2003-dual-audio-hindi-org-480p-bluray-x264-450mb/"
    },
    {
        id: 6,
        Image: require("../assets/images/marvel/hulkTwo.jpg"),
        name: "The Incredible Hulk (2008) 480p BluRay x264",
        star: "Edward Norton, Liv Tyler, Tim Roth, William Hurt",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/hulkTwoOne.jpg"),
        writers: "Zak Penn, Zak Penn, Stan Lee",
        imdb: "6.7/10",
        director: "Louis Leterrier",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Depicting the events after the Gamma Bomb. ‘The Incredible Hulk’ tells the story of Dr Bruce Banner, who seeks a cure to his unique condition, which causes him to turn into a giant green monster under emotional stress. Whilst on the run from military which seeks his capture, Banner comes close to a cure. But all is lost when a new creature emerges; The Abomination.",
        movieLink: "https://ssrmovies.yachts/the-incredible-hulk-2008-dual-audio-hindi-480p-bluray-x264-350mb-2/"
    },
    {
        id: 7,
        Image: require("../assets/images/marvel/thor.jpg"),
        name: "Thor (2011) 1080p 720p 480p BluRay x264",
        star: "Chris Hemsworth, Anthony Hopkins, Natalie Portman",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/thorOne.jpg"),
        writers: "Ashley Miller, Zack Stentz, Don Payne",
        imdb: "7.0/10",
        director: "Kenneth Branagh",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "The warrior Thor (Chris Hemsworth) is cast out of the fantastic realm of Asgard by his father Odin (Sir Anthony Hopkins) for his arrogance and sent to Earth to live amongst humans. Falling in love with scientist Jane Foster (Natalie Portman) teaches Thor much-needed lessons, and his new-found strength comes into play as a villain from his homeland sends dark forces toward Earth.",
        movieLink: "https://ssrmovies.yachts/thor-2011-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-1gb-esubs/"
    },
    {
        id: 8,
        Image: require("../assets/images/marvel/thorTwo.jpg"),
        name: "Thor: The Dark World (2013) 720p BluRay x264",
        star: "Chris Hemsworth, Natalie Portman, Tom Hiddleston, Anthony Hopkins",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/thorTwoOne.jpg"),
        writers: "Christopher L. Yost, Christopher Markus",
        imdb: "6.9/10",
        director: "Alan Taylor",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Thousands of years ago, a race of beings known as Dark Elves tried to send the universe into darkness by using a weapon known as the Aether. Warriors from Asgard stop them but their leader Malekith escapes to wait for another opportunity. The warriors find the Aether and since it cannot be destroyed, they try to hide it. In the present day, Jane Foster awaits the return of Thor although it has been two years since they last saw once another.",
        movieLink: "https://ssrmovies.yachts/thor-the-dark-world-2013-dual-audio-hindi-org-720p-bluray-1gb-esubs/"
    },
    {
        id: 9,
        Image: require("../assets/images/marvel/rang.jpg"),
        name: "Thor: Ragnarok (2017) 480p BluRay x264",
        star: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba",
        geners: "Action, Adventure, Comedy, Fantasy, Sci-Fi",
        screenShot: require("../assets/images/marvel/rangOne.jpg"),
        writers: "Eric Pearson, Craig Kyle, Christopher L. Yost, Stan Lee",
        imdb: "7.9/10",
        director: "Taika Waititi",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his homeworld and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.",
        movieLink: "https://ssrmovies.yachts/thor-ragnarok-2017-dual-audio-hindi-480p-bluray-x264-400mb-esubs/"
    },
    {
        id: 10,
        Image: require("../assets/images/marvel/love.jpg"),
        name: "Thor: Love and Thunder (2022) 1080p 720p 480p WEB-DL x264",
        star: "Chris Hemsworth, Natalie Portman, Christian Bale",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/marvel/loveOne.jpg"),
        writers: "Taika Waititi, Jennifer Kaytin Robinson, Stan Lee",
        imdb: "6.7/10",
        director: "Taika Waititi",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
        movieLink: "https://ssrmovies.yachts/thor-love-and-thunder-2022-dual-audio-hindi-org-1080p-720p-480p-web-dl-esubs/"
    },
    {
        id: 11,
        Image: require("../assets/images/marvel/captain.jpg"),
        name: "Captain America: The First Avenger (2011) 480p BluRay x264",
        star: "Chris Evans, Hayley Atwell, Sebastian Stan, Tommy Lee Jones",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/captainOne.jpg"),
        writers: "Christopher Markus (screenplay), Stephen McFeely",
        imdb: "6.9/10",
        director: "Joe Johnston",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "It is 1942, America has entered World War II, and sickly but determined Steve Rogers is frustrated at being rejected yet again for military service. Everything changes when Dr. Erskine recruits him for the secret Project Rebirth. Proving his extraordinary courage, wits and conscience, Rogers undergoes the experiment and his weak body is suddenly enhanced into the maximum human potential.",
        movieLink: "https://ssrmovies.yachts/captain-america-first-avenger-2011-dual-audio-hindi-480p-bluray-400mb/"
    },
    {
        id: 12,
        Image: require("../assets/images/marvel/captainTwo.jpg"),
        name: "Captain America: The Winter Soldier (2014) 480p BluRay x264",
        star: "Chris Evans, Samuel L. Jackson, Scarlett Johansson, Robert Redford",
        geners: "Action, Adventure, Sci-Fi, Thriller",
        screenShot: require("../assets/images/marvel/captainTwoOne.jpg"),
        writers: "Christopher Markus (screenplay by), Stephen McFeely",
        imdb: "7.7/10",
        director: "Anthony Russo, Joe Russo",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "For Steve Rogers, awakening after decades of suspended animation involves more than catching up on pop culture; it also means that this old school idealist must face a world of subtler threats and difficult moral complexities. That becomes clear when Director Nick Fury is killed by the mysterious assassin, the Winter Soldier, but not before warning Rogers that SHIELD has been subverted by its enemies.",
        movieLink: "https://ssrmovies.yachts/captain-america-winter-soldier-2014-dual-audio-hindi-480p-bluray-450mb/"
    },
    {
        id: 13,
        Image: require("../assets/images/marvel/captainThree.jpg"),
        name: "Captain America: Civil War (2016) 720p BluRay x264",
        star: "Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/captainThreeOne.jpg"),
        writers: "Christopher Markus (screenplay by), Stephen McFeely",
        imdb: "7.8/10",
        director: "Anthony Russo, Joe Russo",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "With many people fearing the actions of super heroes, the government decides to push for the Hero Registration Act, a law that limits a hero’s actions. This results in a division in The Avengers. Iron Man stands with this Act, claiming that their actions must be kept in check otherwise cities will continue to be destroyed, but Captain America feels that saving the world is daring enough and that they cannot rely on the government to protect the world.",
        movieLink: "https://ssrmovies.yachts/captain-america-civil-war-2016-dual-audio-hindi-720p-bluray-1-1gb/"
    },
    {
        id: 14,
        Image: require("../assets/images/marvel/black.jpg"),
        name: "Black Panther (2018) 720p BluRay x264",
        star: "Chadwick Boseman, Michael B. Jordan, Lupita Nyong’o, Danai Gurira",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/blackOne.jpg"),
        writers: "Ryan Coogler, Joe Robert Cole, Stan Lee",
        imdb: "7.3/10",
        director: "Ryan Coogler",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "After the events of Captain America: Civil War, King T’Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country’s new leader. However, T’Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje",
        movieLink: "https://ssrmovies.yachts/black-panther-2018-dual-audio-hindi-720p-bluray-x264-1-4gb-esubs/"
    },
    {
        id: 15,
        Image: require("../assets/images/marvel/blackTwo.jpg"),
        name: "Black Panther: Wakanda Forever (2022) 1080p 720p 480p BluRay x264",
        star: "Letitia Wright, Lupita Nyong’o, Danai Gurira",
        geners: "Action, Adventure, Drama",
        screenShot: require("../assets/images/marvel/blackTwoOne.jpg"),
        writers: "Ryan Coogler, Joe Robert Cole",
        imdb: "7.3/10",
        director: "Ryan Coogler",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T’Challa.",
        movieLink: "https://ssrmovies.yachts/black-panther-wakanda-forever-2022-english-org-1080p-720p-480p-bluray-esubs/"
    },
    {
        id: 16,
        Image: require("../assets/images/marvel/avenger.jpg"),
        name: "Avengers: Age of Ultron (2015) 720p BluRay x264",
        star: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/avengerOne.jpg"),
        writers: "Joss Whedon, Stan Lee, Jack Kirby",
        imdb: "7.3/10",
        director: "Joss Whedon",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Tony Stark creates the Ultron Program to protect the world, but when the peacekeeping program becomes hostile, The Avengers go into action to try and defeat a virtually impossible enemy together. Earth’s mightiest heroes must come together once again to protect the world from global extinction.",
        movieLink: "https://ssrmovies.yachts/avengers-age-of-ultron-2015-dual-audio-hindi-720p-bluray-1-1gb-esubs/"
    },
    {
        id: 17,
        Image: require("../assets/images/marvel/infi.jpg"),
        name: "Avengers: Infinity War (2018) 720p BluRay x264",
        star: "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/infiOne.jpg"),
        writers: "Christopher Markus (screenplay by), Stephen McFeely",
        imdb: "8.4/10",
        director: "Anthony Russo, Joe Russo",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
        movieLink: "https://ssrmovies.yachts/avengers-infinity-war-2018-dual-audio-hindi-720p-bluray-1-4gb-esubs/"
    },
    {
        id: 18,
        Image: require("../assets/images/marvel/end.jpg"),
        name: "Avengers: Endgame (2019) 1080p 720p 480p BluRay x264",
        star: "Robert Downey Jr., Chris Evans, Mark Ruffalo",
        geners: "Action, Adventure, Drama",
        screenShot: require("../assets/images/marvel/endOne.jpg"),
        writers: "Christopher Markus, Stephen McFeely, Stan Lee",
        imdb: "8.4/10",
        director: "Anthony Russo, Joe Russo",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos’s actions and undo the chaos to the universe, no matter what consequences may be in store, and no matter who they face…",
        movieLink: "https://ssrmovies.yachts/avengers-endgame-2019-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {
        id: 19,
        Image: require("../assets/images/marvel/guard.jpg"),
        name: "Guardians of the Galaxy (2014) 480p BluRay x264",
        star: "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
        geners: "Action, Adventure, Comedy, Sci-Fi",
        screenShot: require("../assets/images/marvel/guardOne.jpg"),
        writers: "James Gunn, Nicole Perlman, Dan Abnett",
        imdb: "8.0/10",
        director: "James Gunn",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "After stealing a mysterious orb in the far reaches of outer space, Peter Quill from Earth, is now the main target of a manhunt led by the villain known as Ronan the Accuser. To help fight Ronan and his team and save the galaxy from his power, Quill creates a team of space heroes known as the “Guardians of the Galaxy” to save the world.",
        movieLink: "https://ssrmovies.yachts/guardians-of-the-galaxy-2014-dual-audio-hindi-480p-bluray-400mb-esubs/"
    },
    {
        id: 20,
        Image: require("../assets/images/marvel/guardTwo.jpg"),
        name: "Guardians of the Galaxy Vol. 2 (2017) 720p BluRay x264",
        star: "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel",
        geners: "Action, Adventure, Comedy, Sci-Fi",
        screenShot: require("../assets/images/marvel/guardTwoOne.jpg"),
        writers: "James Gunn, Dan Abnett, Andy Lanning",
        imdb: "7.6/10",
        director: "James Gunn",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "After saving Xandar from Ronan’s wrath, the Guardians are now recognized as heroes. Now the team must help their leader Star Lord (Chris Pratt) uncover the truth behind his true heritage. Along the way, old foes turn to allies and betrayal is blooming. And the Guardians find that they are up against a devastating new menace who is out to rule the galaxy.",
        movieLink: "https://ssrmovies.yachts/guardians-of-the-galaxy-vol-2-2017-dual-audio-hindi-720p-bluray-1-2gb/"
    },
    {
        id: 21,
        Image: require("../assets/images/marvel/guardThree.jpg"),
        name: "The Guardians of the Galaxy Holiday Special (2022) 1080p 720p 480p WEB-DL x264",
        star: "Chris Pratt, Pom Klementieff, Dave Bautista",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/marvel/guardThreeOne.jpg"),
        writers: "James Gunn",
        imdb: "7.9/10",
        director: "James Gunn",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Watch the Guardians Star-Lord, Gamora, Drax, Rocket, and Groot engage in some spirited shenanigans in an all-new original special created for Disney+.",
        movieLink: "https://ssrmovies.yachts/guardians-of-the-galaxy-holiday-special-2022-english-org-1080p-720p-480p-web-dl/"
    },
    {
        id: 22,
        Image: require("../assets/images/marvel/guardFour.jpg"),
        name: "Guardians of the Galaxy Vol. 3 (2023) 1080p 720p 480p WEB-DL x264",
        star: "Chris Pratt, Chukwudi Iwuji, Bradley Cooper",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/marvel/guardFourOne.jpg"),
        writers: "James Gunn",
        imdb: "8.2/10",
        director: "James Gunn",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own – a mission that could mean the end of the Guardians if not successful.",
        movieLink: "https://ssrmovies.yachts/guardians-of-the-galaxy-vol-3-2023-dual-audio-hindi-cleaned-1080p-720p-480p-web-dl-x264/"
    },
    {
        id: 23,
        Image: require("../assets/images/marvel/ant.jpg"),
        name: "Ant-Man (2015) 720p BluRay x264",
        star: "Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll",
        geners: "Action, Adventure, Comedy, Sci-Fi",
        screenShot: require("../assets/images/marvel/antOne.jpg"),
        writers: "Edgar Wright, Joe Cornish, Adam McKay",
        imdb: "7.3/10",
        director: "Peyton Reed",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Armed with the astonishing ability to shrink in scale but increase in strength, con-man Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
        movieLink: "https://ssrmovies.yachts/ant-man-2015-dual-audio-hindi-org-720p-bluray-x264-950mb-esubs/"
    },
    {
        id: 24,
        Image: require("../assets/images/marvel/antTwo.jpg"),
        name: "Ant-Man and the Wasp (2018) 720p BluRay",
        star: "Paul Rudd, Evangeline Lilly, Michael Peña",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/marvel/antTwoOne.jpg"),
        writers: "Chris McKenna, Erik Sommers",
        imdb: "7.1/10",
        director: "Peyton Reed",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
        movieLink: "https://ssrmovies.yachts/ant-man-2-2018-dual-audio-hindi-org-720p-bluray-x264-1-1gb-esubs/"
    },
    {
        id: 25,
        Image: require("../assets/images/marvel/antThree.jpg"),
        name: "Ant-Man and the Wasp: Quantumania (2023) 1080p 720p 480p HDTC x264",
        star: "Paul Rudd, Evangeline Lilly, Jonathan Majors",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/marvel/antThreeOne.jpg"),
        writers: "Jack Kirby, Jeff Loveness",
        imdb: "6.6/10",
        director: "Peyton Reed",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures and embark on an adventure that goes beyond the limits of what they thought was possible.",
        movieLink: "https://ssrmovies.yachts/ant-man-and-the-wasp-quantumania-2023-dual-audio-hindi-cleaned-1080p-720p-480p-hdtc-x264/"
    },
    {
        id: 26,
        Image: require("../assets/images/marvel/doctor.jpg"),
        name: "Doctor Strange (2016) 1080p 720p 480p BluRay x264",
        star: "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/doctorOne.jpg"),
        writers: "Jon Spaihts, Scott Derrickson, C. Robert Cargill",
        imdb: "7.5/10",
        director: "Scott Derrickson",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Marvel’s “Doctor Strange” follows the story of the talented neurosurgeon Doctor Stephen Strange who, after a tragic car accident, must put ego aside and learn the secrets of a hidden world of mysticism and alternate dimensions. Based in New York City’s Greenwich Village, Doctor Strange must act as an intermediary between the real world and what lies beyond, utilising a vast array of metaphysical abilities and artifacts to protect the Marvel Cinematic Universe.",
        movieLink: "https://ssrmovies.yachts/doctor-strange-2016-dual-audio-hindi-org-1080p-720p-480p-bluray-esubs/"
    },
    {
        id: 27,
        Image: require("../assets/images/marvel/doctorTwo.jpg"),
        name: "Doctor Strange in the Multiverse of Madness (2022) 1080p 720p 480p WEB-DL x264",
        star: "Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/doctorTwoOne.jpg"),
        writers: "Michael Waldron",
        imdb: "7.3/10",
        director: "Sam Raimi",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "After the events of Avengers: Endgame, Dr. Stephen Strange continues his research on the Time Stone. But an old friend turned enemy seeks to destroy every sorcerer on Earth, messing with Strange’s plan, causing him to unleash an unspeakable evil",
        movieLink: "https://ssrmovies.yachts/doctor-strange-in-the-multiverse-of-madness-2022-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {
        id: 28,
        Image: require("../assets/images/marvel/marvel.jpg"),
        name: "Captain Marvel (2019) 1080p BluRay",
        star: "Brie Larson, Samuel L. Jackson, Ben Mendelsohn",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/marvelOne.jpg"),
        writers: "Anna Boden, Ryan Fleck",
        imdb: "7.0/10",
        director: "Anna Boden, Ryan Fleck",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "In 1995, on the Kree Empire’s capital planet of Hala, Starforce member Vers suffers from amnesia and recurring nightmares involving an older woman. Yon-Rogg, her mentor and commander, trains her to control her abilities while the Supreme Intelligence, the artificial intelligence that rules the Kree, urges her to keep her emotions in check. During a mission to rescue an undercover operative infiltrating a group of Skrulls, alien shapeshifters with whom the Kree are at war, Vers is captured by Skrull commander Talos.",
        movieLink: "https://ssrmovies.yachts/captain-marvel-2019-dual-audio-hindi-org-1080p-bluray-x264-esubs/"
    },
    {
        id: 29,
        Image: require("../assets/images/marvel/widow.jpg"),
        name: "Black Widow (2021) 720p BluRay x264",
        star: "Scarlett Johansson, Florence Pugh, David Harbour",
        geners: "Action, Adventure, Sci-Fi",
        screenShot: require("../assets/images/marvel/widowOne.jpg"),
        writers: "Eric Pearson, Jac Schaeffer, Ned Benson",
        imdb: "6.8/10",
        director: "Cate Shortland",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "In Marvel Studios’ action-packed spy thriller “Black Widow,” Natasha Romanoff aka Black Widow confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
        movieLink: "https://ssrmovies.yachts/black-widow-2021-imax-dual-audio-hindi-org-720p-bluray-1-2gb-esubs/"
    },
    {
        id: 30,
        Image: require("../assets/images/marvel/sang.jpg"),
        name: "Shang-Chi and the Legend of the Ten Rings (2021) 1080p BluRay x264",
        star: "Simu Liu, Awkwafina, Tony Chiu-Wai Leung",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/sangOne.jpg"),
        writers: "Dave Callaham, Destin Daniel Cretton, Andrew Lanham",
        imdb: "7.9/10",
        director: "Destin Daniel Cretton",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
        movieLink: "https://ssrmovies.yachts/shang-chi-and-the-legend-of-the-ten-rings-2021-dual-audio-hindi-org-1080p-bluray-x264-2-3gb-esubs/"
    },
    {
        id: 31,
        Image: require("../assets/images/marvel/enter.jpg"),
        name: "Eternals (2021) 1080p 720p 480p BluRay x264",
        star: "Gemma Chan, Richard Madden, Angelina Jolie",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/enterOne.jpg"),
        writers: "Chloé Zhao, Patrick Burleigh, Ryan Firpo",
        imdb: "6.7/10",
        director: "Chloé Zhao",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Following the events of Avengers: Endgame (2019), an unexpected tragedy forces the Eternals, ancient aliens who have been living on Earth in secret for thousands of years, out of the shadows to reunite against mankind’s most ancient enemy, the Deviants.",
        movieLink: "https://ssrmovies.yachts/eternals-2021-dual-audio-hindi-org-1080p-720p-480p-bluray-x264-esubs/"
    },
    {
        id: 32,
        Image: require("../assets/images/marvel/dead.jpg"),
        name: "Deadpool (2016) 720p BluRay x264",
        star: "Ryan Reynolds, Karan Soni, Ed Skrein, Michael Benyaer",
        geners: "Action, Adventure, Comedy, Sci-Fi",
        screenShot: require("../assets/images/marvel/deadOne.jpg"),
        writers: "Rhett Reese, Paul Wernick",
        imdb: "8.0/10",
        director: "Tim Miller",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "This is the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
        movieLink: "https://ssrmovies.yachts/deadpool-2016-dual-audio-hindi-720p-bluray-x264-950mb-esubs/"
    },
    {
        id: 33,
        Image: require("../assets/images/marvel/deadTwo.jpg"),
        name: "Deadpool 2 (2018) 720p BluRay x264",
        star: "Ryan Reynolds, Josh Brolin, Morena Baccarin, Julian Dennison",
        geners: "Action, Adventure, Comedy, Sci-Fi",
        screenShot: require("../assets/images/marvel/deadTwoOne.jpg"),
        writers: "Rhett Reese, Paul Wernick, Ryan Reynolds",
        imdb: "7.7/10",
        director: "David Leitch",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Foul-mouthed mutant mercenary Wade Wilson (a.k.a. Deadpool), brings together a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg Cable.",
        movieLink: "https://ssrmovies.yachts/deadpool-2-2018-dual-audio-hindi-720p-bluray-x264-1-1gb-esubs/"
    },
    {
        id: 34,
        Image: require("../assets/images/marvel/fan.jpg"),
        name: "Fantastic Four (2005) 480p",
        star: "Ioan Gruffudd, Michael Chiklis, Chris Evans",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/fanOne.jpeg"),
        writers: "Mark Frost, Michael France",
        imdb: "5.7/10",
        director: "Tim Story",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Physicist Reed Richards is convinced evolution was triggered millions of years ago on Earth by clouds of cosmic energy in space and has calculated that one of these clouds is soon going to pass near Earth. Together with his friend, astronaut Ben Grimm, Reed convinces Victor Von Doom, his former classmate at MIT and now CEO of Von Doom Industries, to allow him access to his privately held space station to test the effects of a biological sample of exposure to the cloud.",
        movieLink: "https://ssrmovies.yachts/fantastic-four-2005-dual-audio-hindi-480p-bluray-x264-300mb-esubs/"
    },
    {
        id: 35,
        Image: require("../assets/images/marvel/fanTwo.jpg"),
        name: "Fantastic 4: Rise of the Silver Surfer (2007) 720p",
        star: "Ioan Gruffudd, Jessica Alba, Chris Evans",
        geners: "Action, Adventure, Fantasy",
        screenShot: require("../assets/images/marvel/fanTwoOne.jpeg"),
        writers: "Don Payne, Mark Frost",
        imdb: "5.6/10",
        director: "Tim Story",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "As Reed Richards and Sue Storm prepare for their wedding, a silver object enters Earth’s atmosphere, creating immense craters around the world. General Hager directs Reed to track and identify its movements. During the wedding, Reed’s systems detect the phenomenon approaching New York City, which suffers a blackout from the object’s electromagnetic pulses. Johnny Storm pursues the object, discovering it to be a silver humanoid on a flying surfboard.",
        movieLink: "https://ssrmovies.yachts/fantastic-four-2-2007-dual-audio-hindi-720p-bluray-800mb-esubs/"
    },
    {
        id: 36,
        Image: require("../assets/images/marvel/fanThree.jpg"),
        name: "Fantastic Four (2015) 720p",
        star: "Miles Teller, Kate Mara, Michael B. Jordan",
        geners: "Action, Adventure, Drama",
        screenShot: require("../assets/images/marvel/fanThreeOne.jpeg"),
        writers: "Jeremy Slater, Simon Kinberg",
        imdb: "4.3/10",
        director: "Josh Trank",
        language: "Hindi (ORG 5.1) + English (ORG 2.0)",
        story: "Four young outsiders teleport to an alternate and dangerous universe which alters their physical form in shocking ways. The four must learn to harness their new abilities and work together to save Earth from a former friend turned enemy.",
        movieLink: "https://ssrmovies.yachts/fantastic-four-2015-dual-audio-hindi-720p-bluray-x264-750mb-esubs/"
    },
]

export default Marvel;