const SouthDetails = [
    {   
        id: 1,
        Image: require("../assets/images/south/balupu.jpg"),
        name: "Balupu (2013) 1080p 720p 480p WEB-DL x264",
        star: "Ravi Teja, Shruti Haasan, Anjali",
        geners: "Action, Comedy",
        screenShot: require("../assets/images/south/balupuOne.jpg"),
        writers: "Kona Venkat, K.S. Ravindra, Veligonda Srinivas",
        imdb: "6.1/10",
        director: "Gopichand Malineni",
        language: "Hindi (ORG 2.0)",
        story: "Ravi (Ravi Teja) works as a collection agent of ICICI in Bangalore and leads a happy life along with his friends and his father Mohan Rao (Prakash Raj) who wishes to see Ravi married to a girl soon. Once Ravi rushes to a Hospital where his friend (‘Satyam’ Rajesh) is admitted as he tried to commit suicide by drinking nail polish solution and asks the reason for it. Then he describes about the traits of Shruti (Shruti Haasan) and her uncle Crazy Mohan (Brahmanandam). The duo have a habit of cheating gullible young men including his friend and Ravi decides to teach them a lesson.",
        movieLink: "https://ssrmovies.yachts/balupu-2013-hindi-dubbed-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 2,
        Image: require("../assets/images/south/bholla.jpg"),
        name: "Bholaa Shankar (2023) 1080p 720p 480p WEB-DL x264",
        star: "Chiranjeevi, Tamannaah Bhatia, Keerthy Suresh",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/bhollaOne.jpg"),
        writers: "Adi Narayana, Siva, Mamidala Thirupathi",
        imdb: "3.2/10",
        director: "Meher Ramesh",
        language: "Hindi (ORG 5.1)",
        story: "A doting brother tries to hunt down notorious criminals who had harmed his sister.",
        movieLink: "https://ssrmovies.yachts/bholaa-shankar-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 3,
        Image: require("../assets/images/south/chatrapati.jpg"),
        name: "Chatrapathi (2023) 1080p 720p 480p HDTV x264",
        star: "Sai Srinivas Bellamkonda, Nushrratt Bharuccha, Karan Singh Chhabra",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/chatrapatiOne.jpg"),
        writers: "A. Mahadev, Vijayendra Prasad, Mayur Puri",
        imdb: "8.8/10",
        director: "V.V. Vinayak",
        language: "Hindi (ORG 2.0)",
        story: "Shivaji and his family are uprooted from their community in Sri Lanka and wind up as bonded labourers in Visakhapatnam. The situation worsens when his jealous stepbrother enters his life.",
        movieLink: "https://ssrmovies.yachts/chatrapathi-2023-hindi-org-2-0-1080p-720p-480p-hdtv-x264/"
    },
    {   
        id: 4,
        Image: require("../assets/images/south/golondaaj.jpg"),
        name: "Golondaaj (2021) 1080p 720p 480p WEB-DL x264",
        star: "Dev, Alexx O’Nell, Srikanta Acharya",
        geners: "Sport",
        screenShot: require("../assets/images/south/golondaajOne.jpg"),
        writers: "Dhrubo Banerjee, Anirban Bhattacharya, Ruchita Chatterji",
        imdb: "7.3/10",
        director: "Dhrubo Banerjee",
        language: "Hindi (ORG 2.0)",
        story: "The life of Nagendra Prasad Sarbadhikari, who is known as the father of Indian football at a time when football lovers dared to take on the British and chalk their own identity.",
        movieLink: "https://ssrmovies.yachts/golondaaj-2021-hindi-org-1080p-720p-480p-web-dl-x264/"
    },
    {   
        id: 5,
        Image: require("../assets/images/south/ips.jpg"),
        name: "IPC 376 (2021) 1080p 720p 480p WEB-DL x264",
        star: "Nandita Shwetha, Aryan, Meghana Ellen",
        geners: "Drama, Horror, Mystery",
        screenShot: require("../assets/images/south/ipsOne.jpg"),
        writers: "Ramkumar",
        imdb: "4.0/10",
        director: "Ramkumar",
        language: "Hindi (ORG 2.0)",
        story: "The plot revolves around a police inspector and an unknown informer who conveys about future murders in a mysterious way. Will she be able to find the informer?",
        movieLink: "https://ssrmovies.yachts/ipc-376-2021-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 6,
        Image: require("../assets/images/south/kabzaa.jpg"),
        name: "Kabzaa (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Upendra, Sudeep, Shriya Saran",
        geners: "Action, Crime, Drama",
        screenShot: require("../assets/images/south/kabzaaOne.jpg"),
        writers: "M Chandramouli, R. Chandru",
        imdb: "8.9/10",
        director: "R. Chandru",
        language: "Hindi (ORG 2.0)",
        story: "In 1947 a Gandhi follower and a freedom fighter were brutally attacked. Due to unavoidable circumstances, the freedom fighter son gets trapped in the mafia world and the story revolves between 1942 to 1986.",
        movieLink: "https://ssrmovies.yachts/kabzaa-2023-amzn-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 7,
        Image: require("../assets/images/south/liger.jpg"),
        name: "Liger (2022) 1080p 720p 480p WEB-DL x264",
        star: "Mike Tyson, Ananya Panday, Vijay Deverakonda",
        geners: "Action, Drama, Romance",
        screenShot: require("../assets/images/south/ligerOne.jpg"),
        writers: "Puri Jagannadh, Prashant Pandey, A.R. Sreedhar",
        imdb: "3.1/10",
        director: "Puri Jagannadh",
        language: "Hindi (ORG 2.0)",
        story: "A story about martial arts, dreams and star crossed lovers. Liger is an MMA fighter who trains hard and rises up the ranks with one goal in mind, to fight like his idol, world renowned MMA fighter Mark Anderson and get noticed by …",
        movieLink: "https://ssrmovies.yachts/liger-2022-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 8,
        Image: require("../assets/images/south/malik.jpg"),
        name: "Malikappuram (2022) 1080p 720p 480p WEB-DL x264",
        star: "Unni Mukundan, Alphy Panjikaran, Saiju Kurup",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/malikOne.jpg"),
        writers: "Abhilash Pillai",
        imdb: "8.3/10",
        director: "Vishnu Sasi Shankar",
        language: "Hindi (ORG 2.0)",
        story: "An intense desire of Kallu an 8 year old girl from Panchalimedu village to visit Sabarimala.",
        movieLink: "https://ssrmovies.yachts/malikappuram-2022-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 9,
        Image: require("../assets/images/south/mavareen.jpg"),
        name: "Maaveeran (2023) 1080p 720p 480p WEB-DL x264",
        star: "Sivakarthikeyan, Aditi Shankar, Mysskin",
        geners: "Action, Drama, Thriller",
        screenShot: require("../assets/images/south/mavareenOne.jpg"),
        writers: "Madonne Ashwin",
        imdb: "7.6/10",
        director: "Madonne Ashwin",
        language: "Hindi (ORG 2.0)",
        story: "A cowardly cartoonist starts being ‘controlled’ by a cartoon action figure, and takes on a corrupt politician.",
        movieLink: "https://ssrmovies.yachts/maaveeran-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 10,
        Image: require("../assets/images/south/michal.jpg"),
        name: "Michael (2023) 1080p 720p 480p WEB-DL x264",
        star: "Vijay Sethupathi, Sundeep Kishan, Varalaxmi Sarathkumar",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/michalOne.jpg"),
        writers: "Ranjit Jeyakodi",
        imdb: "5.8/10",
        director: "Ranjit Jeyakodi",
        language: "Hindi (ORG 2.0)",
        story: "The gang fighting over places. A youngster decides to gain control of the area. Can he complete his dream of ruling over the place?",
        movieLink: "https://ssrmovies.yachts/michael-2023-uncut-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 11,
        Image: require("../assets/images/south/o.jpg"),
        name: "O Saathiya (2023) 1080p 720p 480p WEB-DL x264",
        star: "Aryan Gowra, Mishti Chakravarty, Kalpalatha",
        geners: "Comedy, Musical, Romance",
        screenShot: require("../assets/images/south/oOne.jpg"),
        writers: "Deepu, Aryan Gowra",
        imdb: "8.2/10",
        director: "Divya Bhavna",
        language: "Hindi (ORG 2.0)",
        story: "The evolving love story of Arjun and Keerthi and the trials and tribulations they face as they mature from adolescence to adulthood.",
        movieLink: "https://ssrmovies.yachts/o-saathiya-2023-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 12,
        Image: require("../assets/images/south/pam.jpg"),
        name: "Pambattam (2023) 1080p 720p 480p HDTV x264",
        star: "Yaashika Aanand, Salil Ankola, Jeevan",
        geners: "Thriller",
        screenShot: require("../assets/images/south/pamOne.jpg"),
        writers: "V C.Vadivudaiyan",
        imdb: "N/A/10",
        director: "V.C. Vadivudaiyan",
        language: "Hindi (ORG 2.0)",
        story: "Pambattam is an Indian movie directed by V.C. Vadivudaiyan starring Jeevan, Mallika Sherawat, Suman Talwar and Rittika Sen. The feature film is produced by V.Palanivel and the music composed by Amrish.",
        movieLink: "https://ssrmovies.yachts/pambattam-2023-hindi-org-2-0-1080p-720p-480p-hdtv-x264/"
    },
    {   
        id: 13,
        Image: require("../assets/images/south/pizza.jpg"),
        name: "Pizza 3: The Mummy (2023) 1080p 720p 480p WEB-DL x264",
        star: "Kavitha Bharathi, Raveena Daha, Ashwin Kakumanu",
        geners: "Drama, Horror, Thriller",
        screenShot: require("../assets/images/south/pizzaOne.jpg"),
        writers: "Mohan Govind",
        imdb: "4.7/10",
        director: "Mohan Govind",
        language: "Hindi (ORG 2.0)",
        story: "The protagonist on a probe to solve a series of murders that take place exactly where he delivers food.",
        movieLink: "https://ssrmovies.yachts/pizza-3-the-mummy-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 14,
        Image: require("../assets/images/south/pop.jpg"),
        name: "Popcorn (2023) 1080p 720p 480p WEB-DL x264",
        star: "Amin, Nithya Das, Avika Gor",
        geners: "Drama",
        screenShot: require("../assets/images/south/popOne.jpg"),
        writers: "Murali Gandham",
        imdb: "4.6/10",
        director: "Murali Gandham",
        language: "Hindi (ORG 2.0)",
        story: "Sameerana and Pavan, who are strangers, meet with an extreme anger on each other will get stuck in a lift . How the emotions unfold beautifully between them and fall in sincere love in 18 hours is the story. From the extreme anger…",
        movieLink: "https://ssrmovies.yachts/popcorn-2023-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 15,
        Image: require("../assets/images/south/r.jpg"),
        name: "VR (Vikrant Rona) 2022) 1080p 720p 480p WEB-DL x264",
        star: "Sudeep, Nirup Bhandari, Neetha Ashok",
        geners: "Adventure, Drama, Mystery",
        screenShot: require("../assets/images/south/rOne.jpg"),
        writers: "Anup Bhandari, John Mahendran",
        imdb: "8.1/10",
        director: "Anup Bhandari",
        language: "Hindi (ORG 2.0)",
        story: "Almost half a century ago, a remote village in the middle of a tropical rainforest starts witnessing a series of unexplainable events which they attribute to the supernatural.",
        movieLink: "https://ssrmovies.yachts/vr-vikrant-rona-2022-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 16,
        Image: require("../assets/images/south/rama.jpg"),
        name: "Rama Banam (2023) V2 1080p 720p 480p HQ DVDScr x264",
        star: "Jagapathi Babu, NassarKushboo",
        geners: "Action, Drama, Family",
        screenShot: require("../assets/images/south/ramaOne.jpg"),
        writers: "Madhusudan Padamati, Bhupathi Raja",
        imdb: "9.7/10",
        director: "Sriwass",
        language: "Hindi (ORG 2.0)",
        story: "Two siblings, who despite their difference in ideologies come together to fight for their common goal",
        movieLink: "https://ssrmovies.yachts/rama-banam-2023-uncut-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 17,
        Image: require("../assets/images/south/spy.jpg"),
        name: "Spy (2023) 1080p 720p 480p WEB-DL x264",
        star: "Nikhil Siddharth, Iswarya Menon, Aryan Rajesh",
        geners: "Action, Thriller",
        screenShot: require("../assets/images/south/spyOne.jpg"),
        writers: "Anirudh Krishna Murthy, K. Raja Shekhar Reddy",
        imdb: "8.3/10",
        director: "Garry Bh",
        language: "Hindi (ORG 2.0)",
        story: "A R&AW agent unravels the connection between a notorious arms dealer and the hidden secrets of Netaji Subhash Chandra Bose, risking everything to protect India from impending chaos",
        movieLink: "https://ssrmovies.yachts/spy-2023-uncut-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 18,
        Image: require("../assets/images/south/thunivu.jpg"),
        name: "Thunivu (2023) NF 1080p 720p 480p WEB-DL x264",
        star: "Amir, Cibi Bhuvana Chandran, Darshan",
        geners: "Action, Adventure, Thriller",
        screenShot: require("../assets/images/south/thunivuOne.jpg"),
        writers: "H. Vinoth",
        imdb: "7.2/10",
        director: "H. Vinoth",
        language: "Hindi (ORG 2.0)",
        story: "A mysterious mastermind and his team forms a plan and commits bank heists across Chennai, but their motive of the heists remains mysterious.",
        movieLink: "https://ssrmovies.yachts/thunivu-2023-nf-hindi-org-1080p-720p-480p-nf-web-dl-x264-esubs/"
    },
    {   
        id: 19,
        Image: require("../assets/images/south/vathii.jpg"),
        name: "Vaathi (2023) NF 1080p 720p 480p WEB-DL x264",
        star: "Dhanush, Samyuktha Menon, Sai Kumar",
        geners: "Action, Drama",
        screenShot: require("../assets/images/south/vathiiOne.jpg"),
        writers: "Venky Atluri",
        imdb: "7.9/10",
        director: "Venky Atluri",
        language: "Hindi (ORG 2.0)",
        story: "The life of a young man and his struggles against the privatization of education.",
        movieLink: "https://ssrmovies.yachts/vaathi-2023-nf-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 20,
        Image: require("../assets/images/south/virupaksa.jpg"),
        name: "Virupaksha (2023) 1080p 720p 480p HQ DVDScr x264",
        star: "Sai Dharam Tej, Ajay, Rajsekhar Aningi",
        geners: "Action, Drama, Mystery",
        screenShot: require("../assets/images/south/virupaksaOne.jpg"),
        writers: "Sukumar",
        imdb: "8.3/10",
        director: "Karthik Varma Dandu",
        language: "Hindi (ORG 2.0)",
        story: "Mysterious deaths occur in a village due to an unknown person’s occult practice. The whole town is scared of these killings. Will they find the person who causes the deaths? ,problems faced during the process is the rest of the st…",
        movieLink: "https://ssrmovies.yachts/virupaksha-2023-uncut-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
];

export default SouthDetails;