const WebSeriesDetails = [
    {   
        id: 1,
        Image: require("../assets/images/webSeries/bambai.jpg"),
        name: "Bambai Meri Jaan (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Nawab Shah, Sunil Palwal, Jay Singh Rajpoot",
        geners: "Crime, Drama",
        screenShot: require("../assets/images/webSeries/bambaiOne.jpg"),
        writers: "Shujaat Saudagar",
        imdb: "N/A/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A sneak into the post-independence Bombay and streets riddled with crime. An honest cop’s journey as he tries to protect his family.",
        movieLink: "https://ssrmovies.yachts/bambai-meri-jaan-2023-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 2,
        Image: require("../assets/images/webSeries/breaking.jpg"),
        name: "Breaking (2022) 1080p 720p 480p WEB-DL x264",
        star: "John Boyega, Nicole Beharie, Selenis Leyva",
        geners: "Crime, Drama, Thriller",
        screenShot: require("../assets/images/webSeries/breakingOne.jpg"),
        writers: "Abi Damaris Corbin, Kwame Kwei-Armah",
        imdb: "6.8/10",
        director: "Abi Damaris Corbin",
        language: "Hindi (ORG 2.0)",
        story: "A Marine war veteran faces mental and emotional challenges when he tries to reintegrate back into civilian life.",
        movieLink: "https://ssrmovies.yachts/breaking-bad-s04/"
    },
    {   
        id: 3,
        Image: require("../assets/images/webSeries/campus.jpg"),
        name: "Campus Beats (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Shantanu Maheshwari, Shruti Sinha, Sahaj Singh",
        geners: "Drama",
        screenShot: require("../assets/images/webSeries/campusOne.jpg"),
        writers: "N/A",
        imdb: "10.0/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "What starts as an agenda to get closure for her past , a GenZ girl uncovers her hidden dancing talent and in the process experiences the real meaning of friendship, love, freedom and justice in a modern dance academy divided sharply across socio-economic class.",
        movieLink: "https://ssrmovies.yachts/?s=Campus+Beats"
    },
    {   
        id: 4,
        Image: require("../assets/images/webSeries/charli.jpg"),
        name: "Charlie Chopra & The Mystery of Solang Valley (2023) 1080p 720p 480p WEB-DL x264",
        star: "Wamiqa Gabbi, Lara Dutta, Naseeruddin Shah",
        geners: "Mystery",
        screenShot: require("../assets/images/webSeries/charliOne.jpg"),
        writers: "N/A",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A rich man dead, a town full of suspects, narratives filled with lies and an innocent convict. How will Charlie navigate through the mystery when every face hides a secret?",
        movieLink: "https://ssrmovies.yachts/charlie-chopra-the-mystery-of-solang-valley-2023-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 5,
        Image: require("../assets/images/webSeries/continentel.jpg"),
        name: "The Continental: From the World of John Wick (2023) 1080p 720p 480p WEB-DL x264",
        star: "Mel Gibson, Colin Woodell, Mishel Prada",
        geners: "Action, Crime, Thriller",
        screenShot: require("../assets/images/webSeries/continentelOne.jpg"),
        writers: "Greg Coolidge, Shawn Simmons, Kirk Ward",
        imdb: "7.8/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Set in 1970s New York City, The Continental explores the origin of the iconic hotel-for-assassins centerpiece of the John Wick universe seen through the eyes and action of a young Winston Scott.",
        movieLink: "https://ssrmovies.yachts/the-continental-from-the-world-of-john-wick-2023-s01-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 6,
        Image: require("../assets/images/webSeries/groot.jpg"),
        name: "I Am Groot (2023) S02 1080p 720p 480p WEB-DL x264",
        star: "Vin Diesel, Fred Tatasciore, Kaitlyn Robrock",
        geners: "Animation, Short, Action",
        screenShot: require("../assets/images/webSeries/grootOne.jpg"),
        writers: "N/A",
        imdb: "6.7/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A series of shorts featuring the seedling Groot along with several new and unusual characters.",
        movieLink: "https://ssrmovies.yachts/i-am-groot-2023-s02-english-org-5-1-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 7,
        Image: require("../assets/images/webSeries/lucky.jpg"),
        name: "Lucky Guy (2023) S01 720p 480p WEB-DL x264",
        star: "Swagger Sharma, Ankur Pathak, Gauri Chakraborty",
        geners: "Drama, Fantasy",
        screenShot: require("../assets/images/webSeries/luckyOne.jpg"),
        writers: "N/A",
        imdb: "9.0/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The story revolves around a guy named “Lucky” who is apparently the luckiest guy in the world . What happens when he losses his luck after living with it for 20 years of his life . Will he be able to fight back . The story starts from the birth of a child who happens to take birth in an extraordinary positioning of planets favouring his fate forever.",
        movieLink: "https://ssrmovies.yachts/lucky-guy-2023-s01-complete-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 8,
        Image: require("../assets/images/webSeries/mask.jpg"),
        name: "Mask Girl (2023)  S01 720p 480p WEB-DL x264",
        star: "Anzu Lawson, Yeom Hye-ran, Jin-Ah Im",
        geners: "Comedy, Drama, Thriller",
        screenShot: require("../assets/images/webSeries/maskOne.jpg"),
        writers: "N/A",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "An office worker who is insecure about her looks becomes a masked internet personality by night until a chain of ill-fated events overtakes her life.",
        movieLink: "https://ssrmovies.yachts/mask-girl-2023-s01-complete-dual-audio-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 9,
        Image: require("../assets/images/webSeries/my.jpg"),
        name: "MY3 2023 S01 1080p 720p 480p WEB-DL x264",
        star: "Hansika Motwani, Janani Iyer, Shanthnu Bhagyaraj",
        geners: "Comedy, Drama, Sci-Fi",
        screenShot: require("../assets/images/webSeries/myOne.jpg"),
        writers: "M Rajesh’s",
        imdb: "7.3/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The series follows the story of a woman named Jaan (Hansika Motwani) who wakes up in a laboratory with no memory of her past. She soon discovers that she is a robot created by a scientist named Dr. Ashutosh (Mugen Rao). Jaan must now learn to control her powers and use them to stop a mysterious organization that is trying to take over the world.",
        movieLink: "https://ssrmovies.yachts/my3-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 10,
        Image: require("../assets/images/webSeries/one.jpg"),
        name: "One Piece (2023) S01 NF 720p 480p WEB-DL x264",
        star: "Iñaki Godoy, Mackenyu, Emily Rudd",
        geners: "Action, Adventure, Comedy",
        screenShot: require("../assets/images/webSeries/oneOne.jpg"),
        writers: "Steven Maeda, Matt Owens",
        imdb: "8.7/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as ‘One Piece.",
        movieLink: "https://ssrmovies.yachts/one-piece-2023-s01-complete-nf-dual-audio-hindi-org-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 11,
        Image: require("../assets/images/webSeries/ragnarok.jpg"),
        name: "Ragnarok (2023) S03 NF 720p 480p WEB-DL x264",
        star: "David Stakston, Jonas Strand Gravli, Herman Tømmeraas",
        geners: "Action, Drama, Fantasy",
        screenShot: require("../assets/images/webSeries/ragnarokOne.jpg"),
        writers: "Emilie Lebech Kaae, Adam Price",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "In the small fictional town of Edda coming of age people are forced to respond to climate changes. The ice caps are melting at a rate no one had anticipated. People go through long periods of drought. The winters are too warm. More and more frequently, people experience extreme cold bursts. In all ways extreme weather conditions. The world is changing, and some might claim that we’re heading towards a new Ragnarok. Unless someone intervenes in time.",
        movieLink: "https://ssrmovies.yachts/ragnarok-2023-s03-complete-nf-dual-audio-hindi-org-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 12,
        Image: require("../assets/images/webSeries/sach.jpg"),
        name: "Aakhri Sach (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Sanjiv Chopra, Tamannaah Bhatia, Kriti Vij",
        geners: "Thriller",
        screenShot: require("../assets/images/webSeries/sachOne.jpg"),
        writers: "Saurav Dey",
        imdb: "5.6/10",
        director: "Robbie Grewal",
        language: "Hindi (ORG 2.0)",
        story: "A bone chilling history that unravels the twisted ties of fate, hidden secrets of a family and terrifying horrors an investigator has ever seen.",
        movieLink: "https://ssrmovies.yachts/aakhri-sach-2023-s01/"
    },
    {   
        id: 13,
        Image: require("../assets/images/webSeries/scam.jpg"),
        name: "Scam 2003 – The Telgi Story (2023) S01 1080p 720p 480p WEB-DL x264",
        star: "Gagandev Riar, Mukesh Tiwari, Sana Amin Sheikh",
        geners: "Biography, Crime, Drama",
        screenShot: require("../assets/images/webSeries/scamOne.jpg"),
        writers: "N/A",
        imdb: "9.9/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Scam 2003 is the story of Abdul Telgi from fruit seller to the kingpin of the stamp paper scam. In the chase for quick money, he lands on the wrong side of the law. With the help of a corrupt system, he rapidly monopolizes the stamp market, feeding everyone in the food chain, carefully maintaining a low profile. But his success and ego get the better of him.",
        movieLink: "https://ssrmovies.yachts/scam-2003-s01-complete-hindi-org-1080p-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 14,
        Image: require("../assets/images/webSeries/school.jpg"),
        name: "School Friends (2023) S01 720p 480p WEB-DL x264",
        star: "Meenakshi Chugh, Alisha Parveen, Aaditya Gupta",
        geners: "Comedy, Romance",
        screenShot: require("../assets/images/webSeries/schoolOne.jpg"),
        writers: "N/A",
        imdb: "N/A",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "A slice-of-life show that explores the lives of 5 quirky school teenagers who’ve just entered 11th Commerce, as they navigate friendships, heartbreaks, peer pressures, more importantly figuring out who they really want to be. All this in a society that finds it difficult to cope with the fast-changing Gen Z world",
        movieLink: "https://ssrmovies.yachts/school-friends-2023-s01-complete-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 15,
        Image: require("../assets/images/webSeries/secret.jpg"),
        name: "Secret Ingredient 2023 (Part -2) 1080p 720p WEB-DL x264",
        star: "Pooja Singh, Payal Patil, Varun Sagar, Smita Paul",
        geners: "Erotic, Drama",
        screenShot: require("../assets/images/webSeries/secretOne.jpg"),
        writers: "N/A",
        imdb: "N/A",
        director: "Mohammed Ejaz",
        language: "Hindi (ORG 2.0)",
        story: "Flora’s life turns upside down when she discovers that the epitome of pleasure that she claims to be, fails to satisfy her own partner. And soon she learns that Ankush is having an affair with one of her own students.",
        movieLink: "https://ssrmovies.yachts/secret-ingredient-2023-part-02-complete-hindi-org-ullu-1080p-720p-web-dl-x264/"
    },
    {   
        id: 16,
        Image: require("../assets/images/webSeries/sex.jpg"),
        name: "Sex Education (2023) S04 NF 1080p 720p 480p WEB-DL x264",
        star: "Asa Butterfield, Gillian Anderson, Ncuti Gatwa",
        geners: "Comedy, Drama",
        screenShot: require("../assets/images/webSeries/sexOne.jpg"),
        writers: "Laurie Nunn",
        imdb: "8.3/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Socially awkward high school student Otis may not have much experience in the lovemaking department, but he gets good guidance on the topic in his personal sex ed course — living with mom Jean, who is a sex therapist. Being surrounded by manuals, videos and tediously open conversations about sex, Otis has become a reluctant expert on the subject. When his classmates learn about his home life, Otis decides to use his insider knowledge to improve his status at school, so he teams with whip-smart bad girl Maeve to set up an underground sex therapy clinic to deal with their classmates’ problems. But through his analysis of teenage sexuality, Otis realizes that he may need some therapy of his own.",
        movieLink: "https://ssrmovies.yachts/sex-education-2023-s04-complete-nf-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 17,
        Image: require("../assets/images/webSeries/shelter.jpg"),
        name: "Harlan Coben’s Shelter (2023) S01 720p 480p WEB-DL x264",
        star: "6.0/10",
        geners: "Crime, Drama, Mystery",
        screenShot: require("../assets/images/webSeries/shelterOne.jpg"),
        writers: "N/A",
        imdb: "6.0/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The story of Mickey Bolitar and his new life with a mom in rehab, a dead father, an annoying aunt, and a new school in New Jersey.",
        movieLink: "https://ssrmovies.yachts/harlan-cobens-shelter-2023-s01-complete-dual-audio-hindi-org-720p-480p-web-dl-x264-esubs/"
    },
    {   
        id: 18,
        Image: require("../assets/images/webSeries/song.jpg"),
        name: "Song of the Bandits (2023) NF S01 1080p 720p 480p WEB-DL x264",
        star: "Kim Nam-gil, Seohyun, Yoo Jae-myung",
        geners: "Action, Drama, History",
        screenShot: require("../assets/images/webSeries/songOne.jpg"),
        writers: "N/A",
        imdb: "7.5/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "The Koreans who gathered in Gando, today part of northeastern China, for their own reasons and band together to protect their homes during 1910-45 Japanese colonial rule.",
        movieLink: "https://ssrmovies.yachts/song-of-the-bandits-2023-s01-complete-nf-dual-audio-hindi-org-5-1-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
    {   
        id: 19,
        Image: require("../assets/images/webSeries/wheel.jpg"),
        name: "The Wheel of Time (2023) S02 1080p 720p 480p WEB-DL x264",
        star: "Rosamund Pike, Josha Stradowski, Marcus Rutherford",
        geners: " Action, Adventure, Drama",
        screenShot: require("../assets/images/webSeries/wheelOne.jpg"),
        writers: "Rafe Judkins",
        imdb: "7.1/10",
        director: "N/A",
        language: "Hindi (ORG 2.0)",
        story: "Set in a high fantasy world where magic exists, but only some can access it, a woman named Moiraine crosses paths with five young men and women. This sparks a dangerous, world-spanning journey. Based on the book series by Robert Jordan.",
        movieLink: "https://ssrmovies.yachts/the-wheel-of-time-2023-s02-dual-audio-hindi-org-1080p-720p-480p-web-dl-x264-multi-subs/"
    },
];

export default WebSeriesDetails;